CMakeLists.txt
README.md
build_tools/apply_patches.sh
build_tools/fetch_sources.py
cmake/custom_install_amdgpu_compiler.cmake
cmake/custom_install_amdgpu_runtime.cmake
cmake/custom_install_amdgpu_runtime_dev.cmake
components/amd-llvm/CMakeLists.txt
components/rocm-core-libs/CMakeLists.txt
patches/hipify-install-headers-in-include-hipify.patch
patches/rccl-overwrite-generated-files.patch
tests/dlopen-hip.c

This drives adding hipcc, hipify, rocm-smi and rocminfo. hipcc is very particular where things like bitcodes and rocm_agent_enumerator should be.
This necessitates merging the dynamic and dev/compiler staging directories. We need to run hipcc from the staging directory during building of rccl.
Move rocm-cmake as separate project. LLVM references it.
Make sure that subprojects do not reference other rocm stuff in default paths like /opt/rocm.
This seems to be generally done by setting ROCM_PATH. We must the cautious if adding more parts of rocm to avoid contamination with existing installations.
Use our repo tool manifest url as a default.
When fetching sources do not set LLVM to the amd-staging, but let the manifest handle it.

Refactor and add RCCL

---

build_tools/apply_patches.sh
patches/rocm_smi_lib-use-cmake-generator-expr-for-target-out-path-when-stripping.patch
python_projects/runtime/setup.py

Make rocm_smi compatible with CMAKE_PLATFORM_NO_VERSIONED_SONAME by using CMake generator expressions for target library output path.

Fix python package build

---

.github/workflows/build_linux_packages.yml
build_tools/watch_top_processes.sh

The ROCM build includes a fair number of multi-minute link steps, etc and this can be a blackhole when looking at CI logs. Add a script that periodically reports.

Add a background script to periodically report top background processes.

---

CMakeLists.txt
build_tools/fetch_sources.py
cmake/therock_subproject.cmake
cmake/therock_subproject_dep_provider.cmake
math-libs/CMakeLists.txt
math-libs/hipBLAS-common
math-libs/hipBLASLt
math-libs/post_hook_hipBLASLt.cmake
math-libs/pre_hook_hipBLASLt.cmake
patches/rocm-6.3.1/hipBLASLt/0001-Pin-toolchain-environment-variables-from-configure-b.patch

* New cache variable THEROCK_ENABLE_MATH_LIBS.
* Adds hipBLAS-common and hipBLASLt sub-projects.
* Includes a hipBLASLt patch needed to make the library reliably buildable without an /opt/rocm based build (will upstream).

Add hipblaslt to the project.

---

.github/workflows/build_linux_packages.yml
CMakeLists.txt
build_tools/watch_top_processes.sh
cmake/therock_amdgpu_targets.cmake
cmake/therock_subproject.cmake

* Adds a target database, encoded as CMake properties.
* Accepts user target selection flags of:
* -DTHEROCK_AMDGPU_FAMILIES=...
* -DTHEROCK_AMDGPU_TARGETS=...
* Defines a -DTHEROCK_AMDGPU_DIST_BUNDLE_NAME for a next step of building arch-packages.

Extend target selection logic.

---

cmake/therock_subproject.cmake

For example:
```cmake
set(CMAKE_C_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.42.34433/bin/Hostx64/x64/cl.exe")
set(CMAKE_CXX_COMPILER "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.42.34433/bin/Hostx64/x64/cl.exe")
set(CMAKE_LINKER "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.42.34433/bin/Hostx64/x64/link.exe")
set(CMAKE_C_COMPILER_LAUNCHER "ccache")
set(CMAKE_CXX_COMPILER_LAUNCHER "ccache")
```

Quote paths in toolchain to support spaces in paths on Windows.

---

CMakeLists.txt

Logs:
```
[build] [15/123   4% :: 0.278] Building C object CMakeFiles\dlopen-hip.dir\tests\dlopen-hip.c.obj
[build] FAILED: CMakeFiles/dlopen-hip.dir/tests/dlopen-hip.c.obj
[build] ccache C:\PROGRA~2\MICROS~2\2022\BUILDT~1\VC\Tools\MSVC\1442~1.344\bin\Hostx64\x64\cl.exe  /nologo   /DWIN32 /D_WINDOWS /Zi /O2 /Ob1 /DNDEBUG -MD /showIncludes /FoCMakeFiles\dlopen-hip.dir\tests\dlopen-hip.c.obj /FdCMakeFiles\dlopen-hip.dir\ /FS -c D:\projects\TheRock\tests\dlopen-hip.c
[build] D:\projects\TheRock\tests\dlopen-hip.c(1): fatal error C1083: Cannot open include file: 'dlfcn.h': No such file or directory
```
The https://github.com/nod-ai/TheRock/blob/main/tests/dlopen-hip.c file is using a Unix header for `dlopen` of a shared object file. On Windows, an API like …

Skip dlopen test on Windows for now.

---

.github/workflows/publish_build_manylinux_x86_64.yml
CMakeLists.txt
cmake/therock_subproject.cmake
dockerfiles/build_manylinux_x86_64.Dockerfile

* Uses an older form for one feature that was introduced in 3.26.
* Updates the docker image to install 3.25.2.
Fixes #41.

Change cmake min version to 3.25.

---

cmake/therock_subproject.cmake
compiler/CMakeLists.txt

* Adds amd-llvm specific warning flags for sub-projects, disabling some very chatty low signal warnings (`-Wno-documentation-unknown-command -Wno-documentation-pedantic -Wno-unused-command-line-argument`).
* Sets `-DLLVM_ENABLE_PEDANTIC=OFF` for LLVM if building on GCC since it seems that the project doesn't audit this carefully and is full of spam.
* Disables verbose logs of sub-project installation sequences.
Updates #47.

Squelches unhelpful console spam.

---

patches/amd-mainline/hipBLASLt/0001-Add-explicit-CMake-flags-for-specifying-Tensile-tool.patch
patches/amd-mainline/hipBLASLt/0002-Update-find_package-for-msgpack-to-work-with-5.x-and.patch

TensileHost seems to export the ability to include msgpack.hpp to its users and one of them tries to pull it in. This really needs to be a public dep, so I removed the system header surgery and just did it the CMake recommended way. The cost of getting it wrong is catastrophic because you get a sheared dep within the same library across any system installed msgpack and one built private to the project (since the system dep just pollutes /usr/include and will be found regardless if installed).

Change MsgPack dep to be public on TensileHost.

---

base/CMakeLists.txt
cmake/therock_subproject.cmake
compiler/CMakeLists.txt
compiler/artifact-amd-llvm.toml
compiler/post_hook_amd-comgr.cmake
compiler/pre_hook_amd-llvm.cmake
core/CMakeLists.txt
math-libs/CMakeLists.txt

* Builds device-libs as part of amd-llvm, installing into lib/llvm.
* Breaks amd-comgr and hipcc out to standalone builds that install into the root.
* Removes hipcc from the path and adds clr/bin to the PATH, ensuring that clr/dist/bin/hipconfig always has access to its resources needed to identify version, compiler, etc.
* Adds compatibility flags to device-libs to put them in the clang resource dir and the old location.
* For the "amd-hip" toolchain, gets all binaries from clr.
* Removes the need for manual flag pasting to specify bitcode directories.
* There is still a bit of path wonkiness between llvm and clr, but it should be fine until it can be cleaned up more.
Works around #67

Re-organize the compiler build/packaging to more closely match ROCM>= 6.4.

---

patches/amd-mainline/rocm-core/0001-Patch-version-and-getpath-files-for-Windows.patch

Progress on https://github.com/nod-ai/TheRock/issues/36, making a larger portion of https://github.com/ROCm/rocm-core/ compile on Windows.
* The `link.h` and `dlfcn.h` headers do not exist on Windows and are only used when `BUILD_SHARED_LIBS` is set.
* The `PATH_MAX` value, defined in `limits.h`, does not exist on Windows. I opted to use a fixed constant value of `4096`, but `FILENAME_MAX` is also an option (see https://stackoverflow.com/a/65174437).
* Attributes like `__attribute__((visibility("default")))` do not exist on all compilers. Added some boilerplate cross platform versions (different approaches are possible too, this is just what I use on other projects).
1. Made changes in the source folder
2. Committed to a branch (https://github.com/ScottTodd/rocm-core/commit/0dd798f4768ecc9 …

Patch rocm-core to be more compatible with Windows/MSVC.

---

CMakeLists.txt
base/CMakeLists.txt

Together with some other pending PRs, this gets me enough to
1. Fetch sources
2. Configure with CMake
3. Build without errors
Not much is actually getting built, since this disables nearly all projects on Windows, but this is enough to start running CI builds and working on components incrementally.

Preliminary support for the base component on Windows.

---

third-party/CMakeLists.txt
third-party/FunctionalPlus/CMakeLists.txt
third-party/boost/CMakeLists.txt
third-party/eigen/CMakeLists.txt
third-party/fmt/CMakeLists.txt
third-party/frugally-deep/CMakeLists.txt
third-party/msgpack-cxx/CMakeLists.txt
third-party/nlohmann-json/CMakeLists.txt

* No hashes were changed.
* Adds a convenience `therock-third-party` target to build all third party libraries.
Fixes #76

Mirror third-party source archives to a stable location on S3.

---

CMakeLists.txt
build_tools/fetch_sources.py
cmake/finders/FindBLAS.cmake
cmake/finders/FindLAPACK.cmake
cmake/therock_features.cmake
cmake/therock_subproject.cmake
examples/cpp-sdk-user/CMakeLists.txt
math-libs/CMakeLists.txt
math-libs/artifact-solver.toml
math-libs/hipSOLVER
math-libs/post_hook_hipSOLVER.cmake
math-libs/pre_hook_hipSOLVER.cmake
patches/amd-mainline/hipSOLVER/0001-Use-proper-include-path-for-cholmod.h.patch
patches/amd-mainline/rocminfo/0001-Use-idomatic-approach-to-extending-CMAKE_MODULE_PATH.patch
third-party/CMakeLists.txt
third-party/SuiteSparse/CMakeLists.txt
third-party/SuiteSparse/artifact-host-suite-sparse.toml
third-party/host-blas/CMakeLists.txt
third-party/host-blas/artifact-host-OpenBLAS.toml

* Adds host-math group and includes OpenBLAS and SuiteSparse in it to provide libcholmod (so that we have the option to avoid system deps for these).
* Includes upstream patch https://github.com/ROCm/hipSOLVER/pull/364
* Includes upstream patch https://github.com/ROCm/rocminfo/pull/97
Includes workarounds for #82, #83

Add hipSOLVER

---

docs/development/README.md
docs/development/windows_support.md

Progress on https://github.com/nod-ai/TheRock/issues/36, documenting the current dependency requirements, configure options, and some troubleshooting tips.

Add developer documentation for building on Windows.

---

build_tools/fetch_sources.py

This dependency which was added in https://github.com/nod-ai/TheRock/pull/89 contains file paths that are not valid on Windows. Full error logs: https://gist.github.com/ScottTodd/0304483dca863cf6b8b74c15e14dbd85.

Skip incompatible rocprofiler-systems submodules on Windows.

---

base/CMakeLists.txt
build_tools/patch_symlinks_for_windows_ci.sh
patches/amd-mainline/rocprofiler-register/0001-Minimally-working-Windows-MSVC-build.patch

This is gross, and the odd [`.clang-format`](https://github.com/ROCm/rocprofiler-register/blob/amd-staging/.clang-format) file in the rocprofiler-register repo isn't helping. There are probably better design patterns for no-oping the entire project or adding proper support for multiple platforms.
I hacked around enough to get a CMake configure + build that produces a 50KB `rocprofiler-register.dll` on Windows using MSVC and a default CMake build on the default branch from GitHub (standalone, outside of TheRock). The DLL is not expected to work since it is missing function definitions and I did not implement Windows-specific versions of the functions, but this unblocks more parts of build in this project that depend on …

Patch rocprofiler-register for Windows compatibility and enable.

---

.github/workflows/build_windows_packages.yml
CMakeLists.txt
compiler/CMakeLists.txt
compiler/pre_hook_amd-comgr.cmake
compiler/pre_hook_amd-llvm.cmake
patches/amd-mainline/llvm-project/0001-Enable-MSVC-support-in-comgr.patch

We'll want to switch to self-hosted runners and tune the cache to make the build faster soon. This is still under 20 minutes on standard runners though: https://github.com/nod-ai/TheRock/actions/runs/13339298280/job/37260996314.

Enable compiler subprojects on Windows.

---

cmake/therock_subproject.cmake

Matching the style for other comment blocks and making it easier to scan through to see each argument.

Indent comments for therock_cmake_subproject_declare args.

---

.github/workflows/build_windows_packages.yml

The [ccache-action](https://github.com/hendrikmuhs/ccache-action) sometimes fails to set up on self-hosted runners. This explicit usage may be more robust.
This will supersede https://github.com/nod-ai/TheRock/pull/106 (see the discussion at https://github.com/nod-ai/TheRock/pull/106#discussion_r1962015427).
Test | Logs
-- | --
Cold cache | https://github.com/nod-ai/TheRock/actions/runs/13418973609/attempts/1?pr=107
Warm cache | https://github.com/nod-ai/TheRock/actions/runs/13418973609/attempts/2?pr=107

Migrate Windows workflow away from ccache-action.

---

.github/workflows/build_windows_packages.yml

Progress on https://github.com/nod-ai/TheRock/issues/36. These runners are more powerful than the standard GitHub-hosted runners so we can more quickly build large projects like LLVM.
* This needed credential changes that took a bit of trial and error, but the key thing wasn't git not working correctly but the nested `urllib.request` in `fetch_sources.py` not pulling in the right cert even after installing certifi. I fixed this by manually exporting the cert into the environment based on a suggestion from here: https://stackoverflow.com/questions/77442172/ssl-certificate-verify-failed-certificate-verify-failed-unable-to-get-local-is.
* The self-hosted runners have some storage space issues that we are working around with an auxiliary disk mount and some powershell commands.
Sample runs:
* …

Move build_windows_packages to self-hosted runner cluster.

---

.github/workflows/build_windows_packages.yml
docs/development/windows_support.md

Progress on https://github.com/nod-ai/TheRock/issues/36. Putting current status in the docs. Status could also go in the tracking issue but I like the version history in a markdown file and this helps set expectations when following the instructions.
I'll need to look closer at existing ROCm support on Windows to form a strategy for expanding support here. A quick scan through the projects suggests that some math-libs and ml-libs projects can run on Windows already, though they may need carve-outs for other parts of the dep tree that are solidly Linux-only at the moment.

Add subproject status table to Windows support doc.

---

cmake/therock_subproject.cmake
docs/development/windows_support.md

Progress on https://github.com/nod-ai/TheRock/issues/36. This fixes ccache when compiling with `-DCMAKE_BUILD_TYPE=RelWithDebInfo` and MSVC on Windows.
Before:
```
λ ccache --show-stats
Cacheable calls:      0 / 4309 ( 0.00%)
Hits:               0
Direct:           0
Preprocessed:     0
Misses:             0
Uncacheable calls: 4309 / 4309 (100.0%)
Local storage:
Cache size (GB):  0.0 / 50.0 ( 0.00%)
```
After:
```
λ ccache --show-stats
Cacheable calls:   4099 / 4309 (95.13%)
Hits:            4054 / 4099 (98.90%)
Direct:        3482 / 4054 (85.89%)
Preprocessed:   572 / 4054 (14.11%)
Misses:            45 / 4099 ( 1.10%)
Uncacheable calls:  210 / 4309 ( 4.87%)
Local storage:
Cache size (GB):  4.2 / 50.0 ( 8.34%)
Hits:            4054 / 4099 (98.90%)
Misses:            45 / 4099 ( 1.10%) …
```

Enable and document ccache + MSVC workaround for LLVM.

---

patches/amd-mainline/ROCR-Runtime/0001-Search-for-libnuma-with-find_package-before-find_lib.patch
patches/amd-mainline/rocprofiler-sdk/0001-Extend-the-hack-to-propagate-HIP-usage-requirements-.patch
patches/amd-mainline/rocprofiler-sdk/0002-Align-configuration-of-libdrm-with-how-ROCR-does-it.patch
patches/amd-mainline/rocprofiler-sdk/0003-Depend-on-libdw-from-libraries-that-consume-its-head.patch
third-party/sysdeps/linux/elfutils/CMakeLists.txt

* elfutils build does not add the compressor include directories to everywhere that need it.
* ROCR-Runtime uses find_library to find NUMA.
* rocprofiler-sdk uses libdw headers in libraries that do not depend on it.

Fix a couple of items that were causing false dependence on system libs.

---

.github/workflows/build_linux_packages.yml
.github/workflows/ci.yml

* Uses the `configure-aws-credentials` action to retrieve short-lived
credentials using GitHub's OIDC provider
* Creates index of files using the MIT-licensed indexer.py script
* Uploads artifacts and logs to the S3 bucket
* Adds links pointing to the bucket to the job summary
Creating index files and uploading files is to be moved to scripts in a
follow up.

Upload artifacts and logs to S3 bucket

---

.github/workflows/portable_linux_package_matrix.yml

* Sets default permissions explicitly
* Pins (and updates) actions as suggested by the OpenSSF Scorecard
project, see
https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies.
Pinned actions can be upgraded by Dependabot which will be added in a
follow up.

Set default permissions and pin actions

---

.github/workflows/build_linux_packages.yml
.github/workflows/build_python_packages.yml
.github/workflows/build_windows_packages.yml
.github/workflows/publish_build_manylinux_x86_64.yml

Pins the remaining actions to a known tagged release with its hash as suggested by OpenSSF Scorecard, see
https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies.

Pin remaining actions

---

CMakeLists.txt
build_tools/CMakeLists.txt
build_tools/fileset_tool.py
build_tools/tests/fileset_tool_test.py
cmake/therock_artifacts.cmake

Functional changes:
* Artifact archives now always write their manifest first (which for a tar file is important) and preserve the artifact directory structure (archives were being flattened as I hadn't fully thought through the case).
* The `artifact-flatten` command can now operate on exploded artifact directories or artifact archives.
* Target neutral artifacts are now named syntactically like their targetful counterparts but with a "_generic" suffix (e.g. "foo_dev_gfx100" vs "bar_dev_generic"). When working on Python packaging, I found myself regretting that these were syntactically different, as it made pattern matching harder.
* While some of this might be possible with just creative use of `tar` and friends, in my early experience having tried that, there are all kinds of corners …

Uplift how artifacts are handled.

---

.gitignore

This helps keep dependencies isolated, especially when build instructions recommend installing packages: https://github.com/nod-ai/TheRock/blob/766eca85b45e0b532ea50bd561f2fb1f8f1d9726/README.md?plain=1#L13-L17 So far the Windows build is looking like it will also need the `jinja2` and `ruamel.yaml` Python packages.
I configure my CMake builds to use a venv, specifically from VSCode with this setting:
```json
"settings": {
"cmake.configureArgs": [
"-DPython3_EXECUTABLE=${workspaceFolder}/.venv/Scripts/python",
```

Add *.venv to .gitignore.

---

.github/workflows/build_windows_packages.yml
README.md
build_tools/fetch_sources.py
docs/development/windows_support.md

Follow-up to https://github.com/nod-ai/TheRock/pull/128.
* Drop some references to 'repo' and the 'sources/' directory
* Change Windows instructions from requiring symlinks to just recommending them
* Drop repo-specific configuration from Windows workflow

Update docs and scripts after repo to submodules migration.

---

build_tools/patch_linux_so.py

The `follow_symlinks` parameter was introduced with Python 3.12. Instead of checking with `exists()`, `is_symlink()` can be used as the script aims to explicitly remove old links at this stage.
Fixes #135

Fix Python 3.10 issue

---

dockerfiles/build_manylinux_x86_64.Dockerfile

tomllib was added with Python 3.11. For Python 3.10 we need toml.

Install toml

---

dockerfiles/build_manylinux_x86_64.Dockerfile

This reverts commit b90ee024a6322f5eb0ce24fa4912f69138bc9731.
The scripts used to build TheRock need some more work to be compatible with older Python versions.

Revert "Pin Dockerfile to Python 3.10 (#138)"

---

build_tools/fileset_tool.py

`hashlib.file_digest()` was added with Python 3.11. This implements a similar helper function.

Fix using hashlib with Python 3.10

---

.github/workflows/portable_linux_package_matrix.yml
cmake/therock_amdgpu_targets.cmake
cmake/therock_subproject.cmake

This adds some target filtering/fallback logic to aid in target bringup by allowing us to build components that are not yet compatible with the target. Warnings are unconditionally issued in such cases.
See #149, #150

Build for gfx1201 / gfx1150 / gfx1151.

---

cmake/therock_amdgpu_targets.cmake

[gfx115x] Disable kernel generation for hipBLASLt.

---

README.md
base/CMakeLists.txt
base/post_hook_rocm_smi_lib.cmake
base/pre_hook_rocm_smi_lib.cmake
build_tools/save_patches.sh
cmake/therock_subproject_dep_provider.cmake
dockerfiles/pytorch-dev/build_rocm.sh
dockerfiles/pytorch-dev/pytorch_dev_ubuntu_24.04.Dockerfile
external-builds/pytorch/ptbuild.py
patches/amd-mainline/rocm_smi_lib/0001-Miscellaneous-CMake-fixes.patch
third-party/sysdeps/common/sqlite3/CMakeLists.txt

Includes a number of fixes that were found upon building in a more stripped down docker container.
* Make rocm_smi_lib depend on the bundled libdrm.
* Patch rocm_smi_lib to fix some poor hygiene issues that were being masked because the project did not contain a `project` declaration (which the super-project uses for integration).
* Report the PKG_CONFIG_PATH in sub-projects.
* sqlite3ext.h header needs to be exported.
Fixes #162

Adds a pytorch-dev docker.

---

cmake/therock_amdgpu_targets.cmake

AMD RX 7700S is in a dgpu and not an igpu.
See how its a separate graphics module for the Framework Laptop 16 https://frame.work/products/16-graphics-module-amd-radeon-rx-7700s

therock_amdgpu_targets.cmake: RX 7700S is a dgpu

---

build_tools/_therock_utils/hash_util.py
build_tools/fileset_tool.py
build_tools/tests/_therock_utils
build_tools/tests/fileset_tool_test.py

Moves hashlib helpers to `hash_util.py` and adds a test for calculating the hash of a file.

Introduce `hash_util` helper

---

math-libs/BLAS/CMakeLists.txt
third-party/host-blas/CMakeLists.txt
third-party/host-blas/cblas-config.cmake.in

Refactors the host-blas CMake configuration and adds a config file to enable hipBLASLt finding cblas via `find_package()` in pure Config mode.

Refactor to enable hipBLASLt finding CBLAS

---

docs/development/README.md
docs/development/build_system.md
docs/development/dependencies.md

* Added a section talking about `_toolchain.cmake` and `CMAKE_TOOLCHAIN_FILE`
* Formatted "Terminology" section
* Added hyperlinks to "Directory Layout" section for both the directories and the upstream project repositories
* Fixed capitalization of "TheRock" and "ROCm" in a few places

Iterate on build system developer documentation.

---

base/post_hook_rocm_smi_lib.cmake
base/pre_hook_rocm_smi_lib.cmake
math-libs/BLAS/CMakeLists.txt
math-libs/BLAS/artifact-blas.toml
patches/amd-mainline/rocBLAS/0002-Fix-handling-BLIS-and-finding-BLAS.patch
patches/amd-mainline/rocBLAS/0003-Find-rocm_smi-via-config-files.patch
patches/amd-mainline/rocBLAS/0004-Move-blas_ex-common_gemm_ex3-to-different-target.patch

Enables building rocBLAS with `BUILD_CLIENTS_TEST` set to `on`. Furthermore, adds a test artifact to which the client tests get bundled to.

Enable building rocBLAS with client tests

---

CONTRIBUTING.md
README.md

Mostly copied/reference parent contributor guidelines and added a quick pointer from the main readme.md. We really do need a quick release/user of existing artifacts though to make this complete

Add initial contributor guidelines and current status of project

---

patches/amd-mainline/hipFFT/0001-PYTHON3_EXE-should-be-Python3_EXECUTABLE.-Either-way.patch
patches/amd-mainline/rocFFT/0001-Use-build-RPATH-correctly.patch
patches/amd-mainline/rocFFT/0002-Use-proper-casing-for-hip-and-hiprtc-packages.patch
patches/amd-mainline/rocFFT/0003-Use-Python3_Executable-from-FindPython3-not-custom-P.patch

If https://cmake.org/cmake/help/latest/module/FindPython3.html succeeds (and it must, given the `REQUIRED` argument), the `Python3_EXECUTABLE` result variable will be set. This should be used instead of a custom `PYTHON3_EXE` variable. Fixing this allows for these projects to get further in the configure step on Windows when not using the provided `toolchain-windows.cmake` files.

Patch FindPython3 usage in rocFFT and hipFFT.

---

dockerfiles/pytorch-dev/pytorch_dev_ubuntu_24.04.Dockerfile

Adds `libgmock-dev` (provides `gmock/gmock.h`) and installs PyYAML. Those are needed to build the BLAS client tests.

Install newly added dependencies

---

base/post_hook_rocm_smi_lib.cmake

This was changed with commit a8d40a7 and is now restored. It unbreaks building with `THEROCK_BUNDLE_SYSDEPS=ON` if libdrm and libnuma headers are not available on the systems.
Unfortunatly, it breaks `THEROCK_BUNDLE_SYSDEPS=OFF`:
```
[hipBLASLt configure] CMake Error in clients/gtest/CMakeLists.txt:
[hipBLASLt configure]   Imported target "rocm_smi64" includes non-existent path
[hipBLASLt configure]
[hipBLASLt configure]   "TheRock/build/base/rocm_smi_lib/dist/lib/rocm_sysdeps/include"
```
This will be adressed in a follow up and for now we unbreak the default when `THEROCK_BUNDLE_SYSDEPS` is set to `ON`.

Revert change to rocm_smi_lib post_hook

---

math-libs/CMakeLists.txt
math-libs/artifact-prim.toml

Builds tests for rocPRIM, hipCUB and rocThrust which get bundled in the `prim_test` artifact.
Closes #175

Build `prim_test` artifact

---

.github/workflows/portable_linux_package_matrix.yml
cmake/therock_amdgpu_targets.cmake

Using this to generate a more recent release build. I triggered runs of the workflow at https://github.com/ROCm/TheRock/actions/runs/13841786867 and https://github.com/ROCm/TheRock/actions/runs/13843372506 with inputs:
* `package_suffix`: `` (empty string)
* `release_tag`: `mainline-snapshot-2025-03-13`
Now that builds are running, I'll look into restructuring the workflow so it supports a configurable set of targets and is less clicky.

Set release tag and name from workflow inputs.

---

README.md

`tomli` is required for Python 3.10 but not for more recent Python versions.

Update instructions on `tomli`

---

.github/workflows/publish_pytorch_dev_docker.yml

The PR adds `gfx942` target to the `Publish PyTorch Dev Dockers`  workflow.
The image was tested manually on MI300X machine and passes the [smoke tests](https://github.com/ROCm/TheRock/blob/main/external-builds/pytorch/smoke-tests/pytorch_smoke_tests.py).

Build Pytorch Docker Image for gfx942

---

math-libs/BLAS/post_hook_hipBLASLt.cmake
math-libs/BLAS/post_hook_hipSPARSE.cmake
math-libs/BLAS/post_hook_rocBLAS.cmake
math-libs/BLAS/post_hook_rocSPARSE.cmake

If `THEROCK_BUILD_TESTING` isn't set to `ON` targets like `hipblaslt-test` do not exist and thus setting the RPATH in post_hook fails.

Don't set RPATH if targets do not exist

---

.github/workflows/ci.yml
.github/workflows/setup.yml
build_tools/configure_ci.py

Progress on https://github.com/ROCm/TheRock/issues/199. This gives us a place to configure what workflows should do, based on inputs like the files changed and labels applied to a pull request. The approach was inspired by prior work over in https://github.com/iree-org/iree/blob/main/build_tools/github_actions/configure_ci.py. Many features there aren't needed here (yet?) though.
For now all this does is skip `build_linux_packages` and `build_windows_packages` in `ci.yml` if the diff relative to the base commit only modifies files matching certain patterns (like `*.md`). This happens for both `push` and `pull_request` triggers but does not happen for `workflow_dispatch` triggers.
I've done some testing on my fork with various pull requests …

Introduce a new configure_ci script.

---

.github/workflows/verify_docker_image.yml

Follow-up to https://github.com/ROCm/TheRock/pull/185, so this doesn't run on all push triggers (to any branch).

Remove push trigger from verify_docker_image.yml

---

README.md
base/CMakeLists.txt
base/post_hook_rocm_smi_lib.cmake

* Also adds to the doc page for ubuntu to install gmock-dev, since that was needed on my machine to test and not documented.
* Tested by attempting to build rccl without bundled sysdeps. Broke before with the reported error, worked after.
Fixes #198
Fixes #295

Makes the INSTALL_INTERFACE sysdeps include conditioned properly.

---

CMakeLists.txt
base/artifact.toml
build_tools/fileset_tool.py
cmake/therock_global_post_subproject.cmake
cmake/therock_install_linux_build_id_files.cmake
cmake/therock_subproject.cmake
compiler/artifact-hipify.toml
math-libs/CMakeLists.txt
math-libs/artifact-prim.toml

* Linux only.
* If enabled, adds staging install time steps to populate the stage install `.build-id/` directory tree.
* All sub-projects will be augmented to split their debugging files in this way, and the staging install will be done with `--strip`.
* Verified it works by starting gdb and pointing at the debug directory (`set debug-file-directory build/dist/rocm`) and debugging clang (`file build/dist/rocm/lib/llvm/bin/clang`).
* The artifact specific `.build-id` trees can be uploaded to OS specific repositories, served through a symbol server, or hosted on S3 (and gdb can be configured to fetch them by URL as needed).
* Before being usable, we need to tweak debug levels project wide to balance utility with size. And we need to prune the LLVM installation overall: we shouldn't even be …

Add THEROCK_SPLIT_DEBUG_INFO and do split .build-id based debug files if enabled.

---

third-party/sysdeps/linux/libdrm/CMakeLists.txt
third-party/sysdeps/linux/libdrm/inline_amdgpu_ids.sh

* Upstream chose to store the device ids at a static location on the file system. While this perhaps has a use case in a long term support OS situation, it is fine for us to just embed the id/name associations.
* We need relocatable packages, so eliminating this filesystem lookup is helpful.
* This just replaces the amdgpu_asic_id.c with an inline lookup. The ids file is still copied to the output (didn't patch the meson build to exclude it).
* Verified with `rocm-smi -a` on my GPU and also manually hacked the device id list to change my device name (and verified that this gets reported).
Fixes #147

Add libdrm patch to inline device ids.

---

math-libs/BLAS/CMakeLists.txt
math-libs/BLAS/artifact-blas.toml
patches/amd-mainline/hipSOLVER/0001-Work-around-race-condition.patch
patches/amd-mainline/hipSOLVER/0002-Install-hipsolver_client.so.patch

Enable building hipSOLVER clients

---

math-libs/BLAS/artifact-blas.toml
patches/amd-mainline/hipBLAS/0003-Install-libhipblas_fortran.so.patch

`libhipblas_fortran.so` is required by the test and benchmark clients but was not part of an installation and therefore also not included in the artifact so far.

Add missing `libhipblas_fortran.so` to artifact

---

build_tools/_therock_utils/py_packaging.py
build_tools/linux_python_package.py
build_tools/packaging/python/templates/rocm-sdk/src/rocm_sdk/__init__.py
build_tools/packaging/python/templates/rocm-sdk/src/rocm_sdk/_dist_info.py
build_tools/packaging/python/templates/rocm-sdk/src/rocm_sdk/tests/core_test.py
build_tools/packaging/python/templates/rocm-sdk/src/rocm_sdk/tests/devel_test.py
external-builds/pytorch/patches/v2.6.0/pytorch/hipified/0001-Rework-LoadHIP.cmake-to-be-based-purely-on-CMAKE_PRE.patch
external-builds/pytorch/patches/v2.6.0/pytorch/hipified/0002-Generate-composable_kernel-ck-config.h-as-part-of-ma.patch
external-builds/pytorch/patches/v2.6.0/pytorch/hipified/0003-TEMPORARY-Manually-disable-roctx-until-compatibility.patch
external-builds/pytorch/patches/v2.6.0/pytorch/hipified/0004-Pin-cmake-4-since-v4-broke-old-pytorch-builds.patch
external-builds/pytorch/patches/v2.6.0/pytorch/hipified/0005-Preload-rocm-sdk-binaries-if-available.patch
external-builds/pytorch/patches/v2.6.0/third_party/composable_kernel/base/0001-Work-around-ambiguous-cast-of-half_t-__half-in-call-.patch
external-builds/pytorch/patches/v2.6.0/third_party/gloo/hipified/0001-Use-proper-find_package-to-locate-amdhip64.patch

* Devel package includes all runtime artifacts plus explicit additional list.
* rocprofiler-sdk workarounds. It is not ready yet and depends on aqlprofiler (without it, it fails self checks).
* Explicitly include prim in the devel package. Since it is header only, no runtime parts were implemented for it, resulting in it being excluded.
* Miscellaneous patches to pytorch to make it work with rocm-sdk wheels.
With this patch, this build procedure for pytorch on a bare system works: https://gist.github.com/stellaraccident/8fb23a37a76c712643fc27acbc4f62ea
Works around #330

Finish getting pytorch to build with rocm-sdk wheels.

---

CMakeLists.txt
core/.gitignore
core/CMakeLists.txt
docs/development/windows_support.md
patches/amd-mainline/clr/0001-Disable-HIP_PLATFORM-auto-detect-if-already-defined.patch
patches/amd-mainline/clr/0002-Apply-patches-for-PAL-static-library-build.patch

Now we can build parts of [AMD CLR](https://github.com/ROCm/clr) on Windows by using a mix of open source files and precompiled static libraries for [Platform Abstraction Layer (PAL)](https://github.com/GPUOpen-Drivers/pal). Notably, we can build `amdhip64_6.dll`, which I have used together with `amd_comgr_2.dll` (from [amd-llvm](https://github.com/ROCm/llvm-project/tree/amd-staging/amd/comgr)) to successfully run some binaries from [rocm-examples](https://github.com/ROCm/rocm-examples).
Sequencing details:
* The requisite files for the build are not yet open sourced, so I've set up a placeholder `compute-win/` folder covered by `.gitignore` that I and other AMD developers can use for Windows support bring-up.
* The patch for CLR that …

Setup CLR for Windows with PAL static lib patches.

---

patches/amd-mainline/hipFFT/0001-PYTHON3_EXE-should-be-Python3_EXECUTABLE.-Either-way.patch
patches/amd-mainline/hipFFT/0002-Fix-CMAKE_INSTALL_PREFIX-init-behavior-on-Win32.patch
patches/amd-mainline/hipSOLVER/0001-Work-around-race-condition.patch
patches/amd-mainline/hipSOLVER/0002-Install-hipsolver_client.so.patch
patches/amd-mainline/hipSOLVER/0003-Fix-CMAKE_INSTALL_PREFIX-init-behavior-on-Win32.patch
patches/amd-mainline/hipSPARSE/0001-Fix-CMAKE_INSTALL_PREFIX-init-behavior-on-Win32.patch
patches/amd-mainline/rocFFT/0001-Use-build-RPATH-correctly.patch
patches/amd-mainline/rocFFT/0002-Use-proper-casing-for-hip-and-hiprtc-packages.patch
patches/amd-mainline/rocFFT/0003-Use-Python3_Executable-from-FindPython3-not-custom-P.patch
patches/amd-mainline/rocFFT/0004-Fix-CMAKE_INSTALL_PREFIX-init-behavior-on-Win32.patch
patches/amd-mainline/rocSOLVER/0001-Fix-CMAKE_INSTALL_PREFIX-init-behavior-on-Win32.patch
patches/amd-mainline/rocSPARSE/0001-Drop-setting-library-directory-and-rpath.patch
patches/amd-mainline/rocSPARSE/0002-Fix-CMAKE_INSTALL_PREFIX-init-behavior-on-Win32.patch

This changes all locations across the project that use the
```cmake
set(CMAKE_INSTALL_PREFIX "${SOME_PATH_HERE}" CACHE PATH "Install path" FORCE)
```
pattern (specifically with `FORCE`) to only do that if `CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT` is set, per the guidance at https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT.html.
Without this,
1. Our setting here is ignored: https://github.com/ROCm/TheRock/blob/bc656e498e2dc3edce9aa5dac1e06fc363273681/cmake/therock_subproject.cmake#L641
2. Subprojects install into the hardcoded `C:/hipSDK` path
3. Subprojects that depend on other subprojects fail to find expected files since they are searching the wrong locations:
```
[build] [hipFFT …
```

Fix CMAKE_INSTALL_PREFIX init behavior on Win32.

---

.github/workflows/build_linux_packages.yml

Till now, artifacts got pushed to `therock-artifacts/${{github.run_id}}` and logs got pushed to `therock-artifacts/${{github.run_id}}/logs`. If building for multiple GPU-families this resulted in pushing over pre-existing files as the `github.run_id` is the same for the jobs that build for different GPU-families. To work around this:
* Create and push an index file for each GPU-family
* Add the GPU-family in the path to the logs
With this the generic artifacts still get replaced by the latest successful job! This reduces the pressure on storage but logs are therefore misleading. This should be fine util pushing to the bucket is moved into scripts.

Create index files and logs for each GPU family

---

.github/workflows/portable_linux_package_matrix.yml

Refactors the `Portable Linux Package` worflow to build nightly releases whose assets get continously pushed to a release tagged `nightly-release`. Furhter allows to push development release to a release tagged `dev-release`. The latter needs some improvements such as a build number or maybe the build date to sort the files not only based on the git hash (which could be shortened).
Progress on #222

Refactor workflow to release nightly releases

---

cmake/therock_subproject.cmake
docs/development/windows_support.md

Tests for rocPRIM run on my gfx1100 dev machine: https://gist.github.com/ScottTodd/5c33611469aa1df9d39b816acecbb7f0.
I silenced a bunch of warnings that were getting in my way and added some notes to https://github.com/ROCm/TheRock/issues/47 about the remaining warnings since the build logs for rocPRIM were 45MB.
Some warnings will be fixed with newer subproject code. rocPRIM in particular is 2 months outdated on `mainline` compared to `develop`, and commits like https://github.com/ROCm/rocPRIM/commit/678701d13b9c1464d59843ead73816acb1716008 fix warnings by removing code like
```C++
#ifdef _WIN32
#define ROCPRIM_KERNEL __global__ static
#else
#define ROCPRIM_KERNEL __global__
#endif
```
that had been causing warnings:
```
16.8 …
```

Expand Windows support to include prim math libs.

---

cmake/therock_subproject.cmake
docs/development/windows_support.md
math-libs/CMakeLists.txt

Now I can build `librocfft.lib` and `hipfft.lib` with `-DTHEROCK_ENABLE_FFT=ON` on Windows.

Set flags for FFT math libs on Windows.

---

docs/development/windows_support.md
patches/amd-mainline/rocThrust/0001-Forward-CMAKE_BUILD_TYPE-when-building-gtest.patch

I was seeing errors like this:
```
279.4	[119/236  22% :: 279.314] Linking CXX executable test\adjacent_difference.hip.exe
279.4	FAILED: test/adjacent_difference.hip.exe 
282.3	C:\Windows\system32\cmd.exe /C "cd . && D:\projects\TheRock\build\core\clr\dist\lib\llvm\bin\clang++.exe -nostartfiles -nostdlib -DWIN32 -D_CRT_SECURE_NO_WARNINGS -DNOMINMAX -fms-extensions -fms-compatibility -D_ENABLE_EXTENDED_ALIGNED_STORAGE  -Wno-documentation-unknown-command -Wno-documentation-pedantic -Wno-unused-command-line-argument -Wno-ignored-attributes -Wno-unknown-attributes -Wno-duplicate-decl-specifier --hip-path=D:/projects/TheRock/build/core/clr/dist --hip-device-lib-path=D:/projects/TheRock/build/core/clr/dist/lib/llvm/amdgcn/bitcode -O3 …
```

Patch rocThrust gtest build type for Windows compatibility.

---

cmake/therock_subproject.cmake

This, together with https://github.com/ROCm/TheRock/pull/358, fixes test compilation for hipCUB and rocThrust.
Details:
* `-fms-extensions` and `-fms-compatibility` are documented here: https://clang.llvm.org/docs/MSVCCompatibility.html
* Projects like hipCUB set `-D_ENABLE_EXTENDED_ALIGNED_STORAGE` to acknowledge using extended aligned storage: https://github.com/ROCm/hipCUB/blob/40f174daf777856949c624317c16ffbfe93e9108/rmake.py#L105-L108

Add more toolchain flags for Windows, required by math libs.

---

patches/amd-mainline/ROCR-Runtime/0001-Search-for-libnuma-with-find_package-before-find_lib.patch

* Bump submodules (excluding BLAS and MIOpen) to remote heads.
* Re-introduces ROCR-Runtime patch.
The ROCR-Runtime patch was dropped with https://github.com/ROCm/TheRock/pull/317. However, the patch is
currently included in `amd-staging` but not yet in `amd-master` which
is the branch the TheRock's submodule points to. If it is intended to
point to a different branch, this should be addressed in a follow up.

Bump submodules 20250407

---

math-libs/BLAS/CMakeLists.txt
math-libs/CMakeLists.txt

Related to https://github.com/ROCm/TheRock/issues/18. These sub-projects first try to find rocm-cmake (https://github.com/ROCm/rocm-cmake) via either the deprecated `find_package(ROCM ...)` or the newer `find_package(ROCmCMakeBuildTools ...)`. If they fail to find the package, they then proceed to set a cached `rocm_cmake_tag` and download whichever version was chosen using `file(DOWNLOAD ...)`. In order to get a predictable and consistent version of the package, this sets our super-project's `rocm-cmake` project in `BUILD_DEPS` for each package that needs it.
I searched through build logs for messages like
```
2025-04-08T12:16:47.5889391Z -- Resolving system find_package(ROCM) (not found in super-project ZLIB;zstd;AMDDeviceLibs;Clang;LLD;LLVM;amd_comgr;rocm-core;rocprofiler-register;BZip2 …
```

Add missing explicit rocm-cmake BUILD_DEPS.

---

cmake/therock_subproject.cmake
cmake/therock_subproject_dep_provider.cmake
comm-libs/CMakeLists.txt
math-libs/BLAS/CMakeLists.txt

* This strict mode avoids the common problem where a sub-project adds a new find_package dep that was not declared.
* Such cases will now cause an error.
Fixes #18

Extend our package resolver to error if packages are known.

---

patches/amd-mainline/hipBLAS-common/0001-Fix-CMAKE_INSTALL_PREFIX-init-behavior-on-Win32.patch
patches/amd-mainline/hipBLAS/0001-Fix-finding-LAPACK-and-CBLAS.patch
patches/amd-mainline/hipBLAS/0002-Work-around-race-condition.patch
patches/amd-mainline/hipBLAS/0003-Install-libhipblas_fortran.so.patch
patches/amd-mainline/hipBLAS/0004-Fix-CMAKE_INSTALL_PREFIX-init-behavior-on-Win32.patch
patches/amd-mainline/rocBLAS/0001-Update-packaging-in-pip-venv-to-stabilize-setuptools.patch
patches/amd-mainline/rocBLAS/0002-Fail-if-BLIS-is-not-found-but-LINK_BLIS-is-set.patch
patches/amd-mainline/rocBLAS/0003-Find-BLAS-with-find_package.patch
patches/amd-mainline/rocBLAS/0004-Find-rocm_smi-via-config-files.patch
patches/amd-mainline/rocBLAS/0005-Move-blas_ex-common_gemm_ex3-to-different-target.patch
patches/amd-mainline/rocBLAS/0006-Fix-CMAKE_INSTALL_PREFIX-init-behavior-on-Win32.patch

See https://github.com/ROCm/TheRock/issues/343. On Windows, these projects have been force setting `CMAKE_INSTALL_PREFIX` to `C:/hipSDK`, regardless of what any superproject or user requests. The canonical way to set a default install prefix is to first check `CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT`: https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT.html and then _not_ use `FORCE`. These are minimal changes to stop the sub-projects from grossly misbehaving.

Patch win32 install prefixes in several BLAS libraries.

---

.github/workflows/ci.yml

Right now, PR triggers only happen upon opened or labeled. Adding synchronize will help the user experience with PRs, so a new job gets triggered and the previous job gets cancelled
Progress on #221

Updating ci trigger

---

CMakeLists.txt
docs/development/windows_support.md
math-libs/BLAS/CMakeLists.txt
math-libs/BLAS/pre_hook_rocBLAS.cmake

This enables configuring with `-DTHEROCK_ENABLE_BLAS=ON` on Windows and building of hipBLAS-common.
Per https://rocm.docs.amd.com/projects/install-on-windows/en/latest/reference/component-support.html, the [ROCProfiler](https://rocm.docs.amd.com/projects/rocprofiler/en/latest/) program is not supported on Windows today, and users are directed to use [Radeon GPU Profiler](https://gpuopen.com/rgp/) instead. Additionally, the roctracer project reports a fatal error during configuration on Windows: https://github.com/ROCm/roctracer/blob/a847d331ff2886d23fdb7946695df7fe440c5f57/CMakeLists.txt#L38-L41
```cmake
if(WIN32)
message(FATAL_ERROR "Windows build is not supported.")
endif()
```

Skip rocprofiler-sdk on unsupported Windows platform.

---

build_tools/CMakeLists.txt
build_tools/_therock_utils/artifacts.py
build_tools/bootstrap_build.py
build_tools/fileset_tool.py
build_tools/tests/artifacts_test.py
build_tools/tests/fileset_tool_test.py
cmake/therock_subproject.cmake

* Adds a new `bootstrap_build.py` script which can be used to pre-populate a build directory from artifacts.
* Updates the subproject CMake support to detect when this has been done and null out sub-project configure/build/stage steps for so populated entities.
* Refactors some artifact handling code to better share with fileset_tool.py.
* Leaves some notes on how to extend this with artifact hashing and ccache namespace handling.
* Leaves notes on how to stream from S3 in the future, which should enable a pretty serviceable development flow for libraries.

Teach the build how to bootstrap from a prior phase.

---

math-libs/BLAS/CMakeLists.txt

This gets rocBLAS configuring and partially building. Currently blocked by errors like these (see https://github.com/ROCm/TheRock/pull/342):
```
[build] -- Configuring done (0.9s)
[build] -- Generating done (0.4s)
[build] -- Build files have been written to: D:/projects/TheRock/build
[build] [1/4   0% :: 0.009] Re-checking globbed directories...
[build] [1/6  16% :: 345.309] Building sub-project rocBLAS (in background)
[build] FAILED: math-libs/BLAS/rocBLAS/stamp/build.stamp D:/projects/TheRock/build/math-libs/BLAS/rocBLAS/stamp/build.stamp 
[build] C:\Windows\system32\cmd.exe /C "cd /D D:\projects\TheRock\build\math-libs\BLAS\rocBLAS\build && d:\projects\TheRock\.venv\Scripts\python D:/projects/TheRock/build_tools/teatime.py …
```

Start to configure+build rocBLAS on Windows.

---

.github/workflows/test_rocprim.yml
.github/workflows/test_rocthrust.yml
patches/amd-mainline/rocThrust/0001-Forward-CMAKE_BUILD_TYPE-when-building-gtest.patch

* Bumps all submodules, expect hipBLASLt, to remote heads:
hipBLASLt points to a commit at develop whereas the module defaults to mainline.
* Manually keps the Tensile pin.

Bump submodules 20250410

---

CMakeLists.txt
core/CMakeLists.txt

* Makes the windows CLR buildable in OSS if the right support library repo is checked out adjacent (this is a temporary measure to unblock progress).
* Unforks the clr cmake config between windows/linux.
* Adds a check that with MSVC we are building 64bit (since so many of the Windows tools default to 32bit and we do not support that).
Progress on #36

Unfork the Linux/Windows CLR build and use published interop blob.

---

CMakeLists.txt
base/artifact.toml
build_tools/fileset_tool.py
third-party/sysdeps/windows/artifact.toml

* Makes the existing `optional=` tag able to take an OS name like "windows" or "linux" in order to control optionality in a system specific way.
Progress on #36

Re-enable artifact generation on Windows.

---

build_tools/_therock_utils/artifacts.py
build_tools/fileset_tool.py
cmake/therock_testing.cmake
examples/CMakeLists.txt
examples/clean_configure_test_project.cmake
examples/cpp-sdk-user/CMakeLists.txt
examples/cpp-sdk-user/hip-host-test.cpp

* This has nothing to do with the full regression test harness: it just makes the default `ctest` unit tests work on Windows:
* Fixes the example/cpp-sdk-user test so that it sets up the HIP compiler properly and sets the PATH when running tests so that in-tree DLLs can be found.
* Extends the `hip-host-test` to also take an argument for the device ordinal to validate. This can be used for very basic sanity checking that the runtime works at all on a platform.
* Conditions running extended device tests (vs just tests that will pass on a build machine without a GPU) by the `THEROCK_ENABLE_DEVICE_TEST=ON` env var. This lets us get some extended sanity checking in client builds by `$env:THEROCK_ENABLE_DEVICE_TEST=ON`.
* Turns the kernel test into an executable and tests it as well if …

Adapts some in-tree smoke tests to work on Windows.

---

third-party/frugally-deep/CMakeLists.txt
third-party/nlohmann-json/CMakeLists.txt

* Both changes were found to be required upon additional testing of MIOpen.
* Includes a workaround for https://github.com/ROCm/MIOpen/issues/3588
Part of breaking #392 up for landing.

Pin frugally deep and enable json multiple headers.

---

third-party/boost/cmake_project/CMakeLists.txt

* Uses a hack to configure the desired libraries (since the bootstrap.bat is broken and does not parse this).
* Disables x32 builds on Windows.
* Only builds release.
* Uses the b2 install command. This is *really* unforunate but lets us avoid a fragile symlink situation. It has to materialize ~17k headers and will do so regardless of what was asked for. This extends the build time on Windows by dozens of seconds because serial filesystem access at that scale is slow. However, hopefully this overlaps with some other build steps or can be cached.
Have I mentioned before how intolerable Boost is to integrate?

Fix the bundled boost build to configure properly on Windows.

---

.github/workflows/build_linux_packages.yml
.github/workflows/build_windows_packages.yml
.github/workflows/portable_linux_package_matrix.yml
.github/workflows/publish_pytorch_dev_docker.yml
build_tools/fetch_sources.py

Resolves:
- git login issue
- another issue where script tries to patch things not included, causing "no file found" errors. example cmd: `./build_tools/fetch_sources.py --jobs 8 --no-include-math-libs --no-include-ml-frameworks`
Closes #444

Fixing fetch_sources.py for patching

---

.github/workflows/build_windows_packages.yml

- Use static build path in order to allow ccache to hit 
- Removes use of timestamped directory build path
- Uses local temporary disks on Azure VM via kubernetes container `emptyDir` storage mount 
- AKS Node Pool now uses one of these Azure VM sizes: `Standard_D96ads_v6`, `Standard_HX176rs`, `Standard_HB176rs_v4` (Old was Standard_D64s_v3)
- Output logging for free disk space
- Add taint for spot nodes
- modified gha-runner-scale-set arc-runners yaml configuration to include:
```
resources:
limits:
ephemeral-storage: 400Gi
memory: 300Gi
requests:
ephemeral-storage: 10Gi
memory: 300Gi
volumeMounts:
- name: tmpbuild-dir
mountPath: "b:"
- name: src-ccache-dir
mountPath: "s:"
- name: src-ccache-dir
mountPath: /home/runner/_work
tolerations:
- effect: NoSchedule
key: kubernetes.io/os …
```

Update Windows Github Action to use static build path on local disk

---

.github/workflows/test_release_packages.yml

fixing [this issue](https://github.com/ROCm/TheRock/actions/runs/14619097334) where matrix doesn't have test machine available, don't run tests

Ignore if no machine available for release testing

---

.github/workflows/publish_pytorch_dev_docker.yml
.github/workflows/verify_docker_image.yml

Improved from https://github.com/ROCm/TheRock/pull/361 PR
The workflows, `verify_docker_image.yml` and `publish_pytorch_dev_docker.yml`, are needed to be connected since the published docker images should be verified. The current work plan as below:
Publish -> Verify ->Tag the image if verification passed
Used  https://github.com/benc-uk/workflow-dispatch

Invoke Image Verification by Image Publishing using Dispatching

---

external-builds/pytorch/patches/v2.7.0/pytorch/hipified/0001-Rework-LoadHIP.cmake-to-be-based-purely-on-CMAKE_PRE.patch
external-builds/pytorch/patches/v2.7.0/pytorch/hipified/0002-Generate-composable_kernel-ck-config.h-as-part-of-ma.patch
external-builds/pytorch/patches/v2.7.0/pytorch/hipified/0003-TEMPORARY-Manually-disable-roctx-until-compatibility.patch
external-builds/pytorch/patches/v2.7.0/pytorch/hipified/0004-ROCm-enable-hipBLASLt-for-gfx-1102-1150-1151-1201.patch
external-builds/pytorch/patches/v2.7.0/pytorch/hipified/0005-Add-gfx1150-gfx1151-to-hipblaslt-support-list-in-Bla.patch
external-builds/pytorch/patches/v2.7.0/pytorch/hipified/0006-Support-gfx1151-in-aotriton.patch
external-builds/pytorch/patches/v2.7.0/third_party/composable_kernel/base/0001-ck.hpp-define-CK_BUFFER_RESOURCE_3RD_DWORD-for-gfx11.patch
external-builds/pytorch/patches/v2.7.0/third_party/fbgemm/hipified/0001-UtilsAvx512.cpp-fix-r-may-be-used-uninitialized-for-.patch
external-builds/pytorch/ptbuild.py

This change locally patches, configures and builds Pytorch to use hipBLASLt and aotriton for gfx1151 support
* Meant to be used with `AOTRITON_INSTALL_FROM_SOURCE=1` to build Pytorch with flash attention kernels
* [0001-Rework-LoadHIP.cmake-to-be-based-purely-on-CMAKE_PRE.patch](external-builds/pytorch/patches/v2.7.0/pytorch/hipified/0001-Rework-LoadHIP.cmake-to-be-based-purely-on-CMAKE_PRE.patch)
Patch from @stellaraccident updated to Pytorch v2.7-rc10
* [0002-Generate-composable_kernel-ck-config.h-as-part-of-ma.patch](external-builds/pytorch/patches/v2.7.0/pytorch/hipified/0002-Generate-composable_kernel-ck-config.h-as-part-of-ma.patch) and [0003-TEMPORARY-Manually-disable-roctx-until-compatibility.patch](external-builds/pytorch/patches/v2.7.0/pytorch/hipified/0003-TEMPORARY-Manually-dis …

Update pytorch to 2.7-rc10 and enable gfx1151

---

external-builds/pytorch/ptbuild.py

Will do the testing first to build docker images.
Closes #454

Add fix for version_ref -  use `.find` instead of `.index`

---

README.md

prevents following build errors on fresh ubuntu 24.04 install:
[hip-clr configure]   Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY
[hipBLASLt configure]   Could NOT find Python (missing: Python_EXECUTABLE Python_INCLUDE_DIRS
fixes: https://github.com/ROCm/TheRock/issues/462

Update Ubuntu dependencies in documentation

---

CMakeLists.txt
README.md
docs/environment_setup_guide.md

Adds a basic guide for extended information about setting up environments. We are trying to keep the quick start instructions on the main README succinct, and this is the companion to that, which aims to be comprehensive.

Add environment setup guide.

---

.github/workflows/build_linux_packages.yml
.github/workflows/build_windows_packages.yml
build_tools/teatime.py

This causes subproject logs to only be output to the console on failure vs success. Given the state of warning spew in the projects and how hard it is to track through running console logs for this stuff, this is the better setting. All detailed triage needs to happen on log files, which we persist in S3.
Some third-party subprojects which we don't control were already setting this at the project level. Setting at the CI level just lets us exert special control project wise.
Also switches the Linux output to be prefixed by project name instead of fancy expando handles. I've found this to be more ergonomic, especially in non-interactive mode.
Also removes the watch_top_processes thing on Linux. We have better ways to do this now.
Normal users remain subject to the full fury of the …

Adds a magic env var TEATIME_FORCE_INTERACTIVE and sets it to 0 in CI jobs.

---

math-libs/BLAS/CMakeLists.txt

Progress on https://github.com/ROCm/TheRock/issues/36. This is possible now that hipBLASLt builds on Windows.
Tested by building locally, with tests enabled too. I did not actually run the tests though.

Set `-DBUILD_WITH_HIPBLASLT=ON` for rocBLAS on Windows.

---

patches/amd-mainline/hipBLAS/0001-Fix-finding-LAPACK-and-CBLAS.patch
patches/amd-mainline/hipBLAS/0002-Work-around-race-condition.patch
patches/amd-mainline/hipBLAS/0003-Install-libhipblas_fortran.so.patch
patches/amd-mainline/hipBLAS/0004-Fix-CMAKE_INSTALL_PREFIX-init-behavior-on-Win32.patch
patches/amd-mainline/hipBLAS/0005-Adapt-to-some-upstream-hipblas-common-usage-differen.patch
patches/amd-mainline/hipBLAS/0006-Replace-python-with-official-Python3_EXECUTABLE-vari.patch
patches/amd-mainline/rocSPARSE/0001-Drop-setting-library-directory-and-rpath.patch
patches/amd-mainline/rocSPARSE/0002-Fix-CMAKE_INSTALL_PREFIX-init-behavior-on-Win32.patch
patches/amd-mainline/rocSPARSE/0003-Replace-deprecated-reference-GTest-GTest-GTest-gtest.patch
patches/amd-mainline/rocSPARSE/0004-Replace-python-with-official-Python3_EXECUTABLE-vari.patch

Progress on https://github.com/ROCm/TheRock/issues/36. Now I can build the tests for rocSPARSE on Windows.
After calling `find_package(Python3 COMPONENTS Interpreter)`, the result variable `Python3_EXECUTABLE` should be set. This should be used instead of custom discovery or manual setting like in https://github.com/ROCm/rocSPARSE/blob/develop/toolchain-windows.cmake:
```cmake
if (NOT python)
set(python "python") # take default for windows
endif()
```
Docs:
* https://cmake.org/cmake/help/latest/module/FindPython3.html
* https://cmake.org/cmake/help/latest/module/FindPython3.html#result-variables
---
I did not fix up _all_ references to the custom `python` CMake variable. Notably, rocBLAS has more convoluted logic using a virtual environment that needs to be untangled more carefully …

Apply Python3_EXECUTABLE patches to rocSPARSE and hipBLAS.

---

docs/development/windows_support.md

Tests need a bit of help to run, but otherwise seems to be working:
1. I manually copied `rocblas.dll` from `build/math-libs/BLAS/rocBLAS/dist/bin` to `build\math-libs\BLAS\rocSPARSE\dist\bin`
2. Some tests need files from relative paths that aren't copied into the dist dir (they can be found at `build\math-libs\BLAS\rocSPARSE\build\clients\matrices`):
```
.\build\math-libs\BLAS\rocSPARSE\dist\bin\rocsparse-test.exe
...
[ RUN      ] quick/bsrmv.level2/f64_c_10_33_n0p5_n0p5_0p5_1_row_2_NT_0b_zero_0
[       OK ] quick/bsrmv.level2/f64_c_10_33_n0p5_n0p5_0p5_1_row_2_NT_0b_zero_0 (159 ms)
[ RUN      ] quick/bsrmv.level2/f64_c_10_33_n0p5_n0p5_0p5_1_row_2_NT_0b_zero_0_t2
[       OK ] …
```

Mark rocSPARSE as supported on Windows.

---

.github/workflows/portable_linux_package_matrix.yml
.github/workflows/publish_pytorch_dev_docker.yml
build_tools/github_action/amdgpu_family_matrix.py
build_tools/github_action/fetch_package_targets.py

Changes:
- Expanding AMD GPU matrix to support more targets/families
- Adding a workflow_dispatch input option to build specific families
progress on #493 , once this workflow runs, gfx1151 image will be available since prebuilt for 1151 exists. for new targets, we will wait till the 2am run to generate those docker images

Expanding AMD GPU matrix and adding options for package generation

---

math-libs/BLAS/CMakeLists.txt

Progress on https://github.com/ROCm/TheRock/issues/36. Adapted from a commit by @jammm.
hipSOLVER has built with sparse disabled on Windows since ROCm 6.1.0: https://github.com/ROCm/hipSOLVER/blob/bb8408f52a166c5ce587b204c61a51ae44bc1daa/CHANGELOG.md?plain=1#L101 and trying to enable it leads to build errors in SuiteSparse/cholmod: https://gist.github.com/ScottTodd/f4c10fb150e7f4a5b1c016dcbe0b2bf3.
With it disabled, I can build the hipSOLVER library but not its tests. The tests need some environment/CMake variables changed or plumbed through as described here: https://github.com/ROCm/TheRock/issues/36#issuecomment-2843655001.

Disable hipSOLVER BUILD_WITH_SPARSE on Windows.

---

docs/development/windows_support.md
patches/amd-mainline/hipSOLVER/0001-Work-around-race-condition.patch
patches/amd-mainline/hipSOLVER/0002-Install-hipsolver_client.so.patch
patches/amd-mainline/hipSOLVER/0003-Fix-CMAKE_INSTALL_PREFIX-init-behavior-on-Win32.patch
patches/amd-mainline/hipSOLVER/0004-Replace-deprecated-GTest-GTest-with-GTest-gtest.patch
patches/amd-mainline/hipSOLVER/0005-Check-if-rocblas_DIR-env-var-is-set-before-using-it.patch

See https://github.com/ROCm/TheRock/issues/513. This avoids a `Error copying directory from "/bin/rocblas/library" to "D:/projects/TheRock/build/math-libs/BLAS/hipSOLVER/build/clients/staging/library"` build time error in hipSOLVER when the `rocblas_DIR` environment variable is not set for some .dll copying code. I'm not sure yet if that copying code will actually be needed in TheRock, given how we model RUNTIME_DEPS in subprojects. For now when _running_ tests, I'm either manually copying .dll files next to test executables or I'm running with a modified PATH.

Patch hipSOLVER Windows dll copy code that needs env vars.

---

CMakeLists.txt

On Windows, SuiteSparse is not currently used and does not build without errors.
Now I can just about build the CMake `all` target when the math and BLAS libraries are enabled. Need to fully validate that after flushing my patch queue and then eventually get the CI/CD caught up.

Disable HOST_SUITE_SPARSE on Windows.

---

.github/workflows/portable_linux_package_matrix.yml

Noticing build issues and realized that we don't install python packages for portable builds
installing this should fix it, test running [here](https://github.com/ROCm/TheRock/actions/runs/14785966138)

Adding python packages to portable linux builds

---

.github/workflows/portable_linux_package_matrix.yml
build_tools/detail/linux_portable_build_in_container.sh

Works in [this workflow](https://github.com/ROCm/TheRock/actions/runs/14804447398/job/41570165138), fails though bc no release testing doesn't have a matching branch so this is a valid error
#520 was merged it prematurely, but this fixes it!
After this is done, it should have images available, and pytorch images can be properly used

Fixing portable builds pt2

---

docs/development/windows_support.md
ml-libs/CMakeLists.txt

Fixes https://github.com/ROCm/TheRock/issues/525. See that issue for other approaches considered.

Enable MIOpen on Windows by patching Boost MSVC options.

---

external-builds/pytorch/ptbuild.py

Without this, running `ptbuild.py checkout` per https://github.com/ROCm/TheRock/tree/main/external-builds/pytorch#step-1-preparing-sources opens my editor each time a commit is tagged, asking for a tag message.
Here are the details per the docs at https://git-scm.com/docs/git-tag:
1. I have this in my .gitconfig:
```
[tag]
gpgsign = true
```
2. That makes `git tag` commands default to `-s / --sign` behavior on my system
3. Behavior changes based on which options are set:
> If one of `-a`, `-s`, or `-u <key-id>` is passed, the command creates a tag object, and requires a tag message. Unless `-m <msg>` or `-F <file>` is given, an editor is started for the user to type in the tag message.
4. Passing a message (empty or not) changes tags from "lightweight tags" to "annotated tags". From the …

Set empty tags messages during PyTorch checkout.

---

docs/development/windows_support.md

Some files, particularly under `external-builds/pytorch`, get long enough to trigger warnings and errors without this setting.

Recommend git core.longpaths setting on Windows.

---

patches/amd-mainline/hipBLASLt/0001-windows-Find-hipblaslt-library-with-posix-directory-.patch

This fixes the problem where the tensile library was expected to be in the bin directory and some code objects were searched for in the PWD.
Sent upstream as https://github.com/ROCm/hipBLASLt/pull/2049. Landing here to test and unblock windows dev.

[hipblaslt] Add temporary path fixing Windows hipblaslt library location handling

---

.github/workflows/ci.yml

As talked about in Slack, adding simple CI docs to help clarify how CI works right now
Felt best to add to top of CI as this will change over time, and it is in a relevant location. Can move it elsewhere though if needed

Adding CI docs

---

external-builds/pytorch/smoke-tests/README.md
external-builds/pytorch/smoke-tests/pytorch_smoke_tests.py

This will help validate more of the ROCm + PyTorch stack without needing to run larger test suites.
Note that something in the new tests is hanging `pytest` on my system. Tests pass, but the pytest command does not terminate until I kill the process.
See also this discussion thread: https://github.com/ROCm/TheRock/discussions/409#discussioncomment-13032345.

Add PyTorch smoketests for convs.

---

dockerfiles/pytorch-dev/pytorch_dev_ubuntu_24.04.Dockerfile
external-builds/pytorch/build_pytorch_audio.sh
external-builds/pytorch/build_pytorch_torch.sh
external-builds/pytorch/build_pytorch_vision.sh
external-builds/pytorch/checkout_pytorch_all.sh
external-builds/pytorch/env_init.sh

- install pytorch vision and audio to docker images
- add ffmpeg and python-is-python3 to final docker image (ffmpeg required by pytorch audio)
- disable exit on error code on build scripts for the time of execution for pip uninstall as that will fail on cases where there is not previous version of torch/torch vision/torch audio wheel installed
- add possibility to use environment variable to specify whether torch-related scripts will do only a build or only a install part
- check ROCM_HOME environment variable on build scripts

add pytorch vision and audio to docker images

---

patches/amd-mainline/clr/0004-windows-Fix-assembler-error-in-pal-trap-handler.patch

Upstreamed as https://github.com/ROCm/clr/pull/163

[windows] Inline clr patch to fix `.not_s_trap` error message on startup.

---

math-libs/BLAS/artifact-blas.toml

Fixes https://github.com/ROCm/TheRock/issues/522.
The executable files have the `.exe` suffix on Windows, so add a trailing wildcard in the glob patterns. We could also teach [`fileset_tool.py`](https://github.com/ROCm/TheRock/blob/main/build_tools/fileset_tool.py) to try the platform-specific suffix if the file is missing a suffix.
Maybe we could also handle `lib[name].so` -> `[name].dll` and other similar transforms, but I _do not_ see Windows equivalents for `lib/libhipsolver_fortran.so` or `lib/libhipblas_fortran.so`.

[windows] Add BLAS test/bench binaries to dist.

---

math-libs/BLAS/artifact-blas.toml

Fixes https://github.com/ROCm/TheRock/issues/571.
We may want to instead change rocBLAS to output to lib/ on both Windows and Linux.

[windows] Include bin/rocblas/library/** in dist.

---

math-libs/BLAS/CMakeLists.txt
third-party/host-blas/CMakeLists.txt
third-party/host-blas/cblas-config.cmake.in

* The cblas package now delegates to OpenBLAS::OpenBLAS instead of directly importing files.
* OpenBLAS installs to the install root and changes its INSTALL dirs to put files under lib/host-math.
* On Windows, the DLL is output to bin/ instead of lib/host-math/bin.
Verified manually that it functions with #601.

[openblas] Change the vendoring strategy of OpenBLAS for better compat.

---

build_tools/github_action/configure_ci.py
build_tools/github_action/configure_ci_test.py

Context: https://github.com/ROCm/TheRock/issues/199.
Without this, I believe changes to e.g. [`ci_linux.yml`](https://github.com/ROCm/TheRock/blob/main/.github/workflows/ci_linux.yml) or [`test_rocblas.yml`](https://github.com/ROCm/TheRock/blob/main/.github/workflows/test_rocblas.yml) would skip the regular build/test CI.

[ci] Add more workflow file name patterns that trigger CI.

---

.github/workflows/build_linux_packages.yml
.github/workflows/build_windows_packages.yml
.github/workflows/ci.yml
.github/workflows/ci_linux.yml
.github/workflows/ci_windows.yml

Workflows fail if manually dispatched as default permissions get granted in that case and `id-token` permissions are not passed from a calling workfow.

Explicitly grant permissions

---

build_tools/github_action/configure_ci.py
build_tools/github_action/configure_ci_test.py

Context: https://github.com/ROCm/TheRock/issues/199.
Currently, changes to PyTorch patches like https://github.com/ROCm/TheRock/pull/606 run all of our CI workflows, despite having no effect on them<sup>1</sup>. We may expand the scope of these workflows, but we should be mindful of the full build graph until we have sufficient caching and incremental build support working well.
[<sup>1</sup>]: PyTorch is currently covered by [`publish_pytorch_dev_docker.yml`](https://github.com/ROCm/TheRock/blob/main/.github/workflows/publish_pytorch_dev_docker.yml) -> [`verify_docker_image.yml`](https://github.com/ROCm/TheRock/blob/main/.github/workflows/verify_docker_image.yml), with the dockerfile installing from the latest release of TheRock, rather than build from source. Do note however: that …

[ci] Skip CI workflows if only external-builds/ is changed.

---

.github/workflows/build_linux_packages.yml
.github/workflows/build_windows_packages.yml
.github/workflows/test_hipblaslt.yml
.github/workflows/test_hipcub.yml
.github/workflows/test_release_packages.yml
.github/workflows/test_rocblas.yml
.github/workflows/test_rocprim.yml
.github/workflows/test_rocthrust.yml
.github/workflows/test_sanity_check.yml

This starts adjusting token permissions, following recommendations in [1]. With this top-level permissions are set to `contents: read` and further permissions are set at a job level only.
[1] https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions.

Adjust GitHub token permissions

---

.github/workflows/release_portable_linux_packages.yml
build_tools/packaging/python/generate_release_index.py

This adds `generate_release_index.py` to create a release index HTML file that lists all wheels and sdist packages in the subdirectory of a specific bucket to enable installing packages via `pip install -f`.

Create release index for Python packages

---

README.md
docs/development/windows_support.md

* Expand on the overview at the top, mentioning more specific features and replacing "a GitHub actions pipeline _will offer_" with more current "Comprehensive CI/CD pipelines"
* Add support status tables for HIP/ROCm and PyTorch components, broken down by operating system
* Adjust headings for "building from source" instructions
* Adjust style for alerts
* Fix `python3` on Windows (should be `python`)
* Format CMake options using tables instead of lists (easier for copy/paste)

Refresh README with overview, support status, style improvements.

---

RELEASES.md

Refreshes the information on how to install TheRock from tarball releases. Releases were recently renamed from `dev-release` and `nightly-release` to `dev-tarball` and `nightly-tarball`, respectively.

Update information on releases

---

.github/workflows/build_linux_packages.yml
.github/workflows/build_windows_packages.yml
build_tools/create_log_index.py
build_tools/upload_logs_to_s3.py

This PR adds the log upload support when the build target failed within the workflow. It is not using `teatime.py` script

Add log upload support for build target failed

---

external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0001-Rework-LoadHIP.cmake-to-be-based-purely-on-CMAKE_PRE.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0002-Generate-composable_kernel-ck-config.h-as-part-of-ma.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0003-TEMPORARY-Manually-disable-roctx-until-compatibility.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0004-enable-hipBLASLt-for-gfx-1102-1150-1151-1201.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0005-Add-gfx1150-gfx1151-to-hipblaslt-support-list-in-Bla.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0006-Support-gfx1151-in-aotriton.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0007-link-correct-version-of-hsa-runtime-with-c10_hip.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0008-rocm-clang-version-check-fix.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0009-Enable-torchvision-build-with-ROCm-on-Windows-147382.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0010-Include-AOTriton-dependent-sources-in-Windows-build-.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0011-Fix-HIP-Caffe2-Tests-152014.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0012-Disable-hipSPARSE-and-CK-declarations-and-remove-ref.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0013-ROCm-Windows-Enable-USE_ROCM-and-fix-assorted-issues.patch
external-builds/pytorch/patches/pytorch/v2.7.0/third_party/composable_kernel/base/0001-ck.hpp-define-CK_BUFFER_RESOURCE_3RD_DWORD-for-gfx11.patch
external-builds/pytorch/patches/pytorch/v2.7.0/third_party/fbgemm/hipified/0001-UtilsAvx512.cpp-fix-r-may-be-used-uninitialized-for-.patch
external-builds/pytorch/patches/pytorch/v2.7.0/third_party/fbgemm/hipified/0002-Fix-compilation-on-clang-cl.patch

Progress on https://github.com/ROCm/TheRock/issues/589. Fixes https://github.com/ROCm/TheRock/issues/590. Fixes https://github.com/ROCm/TheRock/issues/627.
This is a revised version of a patch from @jammm, made in collaboration with @scottt as well. The diff between the original patch and what I am sending here can be viewed at https://github.com/ScottTodd/TheRock/blob/pytorch-windows-cleanup-wip/external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0014-Cleanup-after-testing-with-clang-cl.patch. Summarizing the delta:
* Revert some changes that were not required in my testing
* Trim some MSVC handling, in favor of focusing on just clang-cl first
* Address hipcc warnings
With this patch, I've been able to build PyTorch wheels with ROCm support on Windows using …

[torch][windows] Apply fixes for PyTorch+ROCm on Windows.

---

README.md
docs/development/windows_support.md

Progress on https://github.com/ROCm/TheRock/issues/36. Closes https://github.com/ROCm/TheRock/pull/395.
This incorporates feedback from multiple developers and testers, hoping to provide enough context for self-service debugging while steering more users towards the happy path (if one even exists) on Windows.
* Clarify support status of each subproject with more links to known issues
* Reorganize "system setup" section to highlight requirements vs recommendations
* Reorganize "Install tools" section to suggest `choco` commands for all installs _then_ explain tools individually
* Move post-install instructions to a new "Important tool settings" section
* Elaborate on MSVC environment init
* Recommend against PowerShell
* Add more information about what "building" does, then flow into …

Refresh Windows support documentation.

---

.gitmodules

This switches rocPRIM and rocThrust from mainline to develop which in both cases is only a few commits ahead of mainline.

Bump rocPRIM and rocThrust and track develop

---

patches/amd-mainline/hipBLAS/0001-Fix-finding-LAPACK-and-CBLAS.patch
patches/amd-mainline/hipBLAS/0002-Work-around-race-condition.patch
patches/amd-mainline/hipBLAS/0003-Install-libhipblas_fortran.so.patch
patches/amd-mainline/hipBLAS/0004-Replace-python-with-official-Python3_EXECUTABLE-vari.patch
patches/amd-mainline/hipBLAS/0005-Setup-Fortran-on-Windows.patch
patches/amd-mainline/hipBLAS/0006-Fix-OpenBLAS-package-name-for-Windows.patch
patches/amd-mainline/hipBLAS/0007-Remove-Windows-third_party_dlls-copying-code.patch

This code is built on shaky assumptions that don't hold inside TheRock. We'll need a better solution for DLL handling that works across projects. That work is tracked at https://github.com/ROCm/TheRock/issues/513.
We had a patch that tried to run this code only if some options were set (https://github.com/ROCm/hipBLAS/pull/1007), but that patch got reverted (https://github.com/ROCm/hipBLAS/pull/1018).
---
The specific issue here is that TheRock does not set `ROCBLAS_PATH`, so this code leads to this error:
```cmake
add_custom_command( TARGET hipblas-test POST_BUILD COMMAND ${CMAKE_COMMAND} ARGS -E copy_directory ${ROCBLAS_PATH}/bin/rocblas/library/ ${PROJECT_BINARY_DIR}/staging/library/)
```
We also don't set any of the other `*_DIR` or `*_PATH` variables, resulting in only these files …

[windows]  Patch hipBLAS to delete dll copying code.

---

.github/workflows/test_release_packages.yml

Currently, test notes are not being appended due to missing output. This will fix that.

Adding missing output for test_release_packages.yml

---

RELEASES.md

* Replaces an outdated link
* Adds a section on Python packages

Re-fresh releases docs

---

README.md

to match https://github.com/ROCm/TheRock/blob/main/docs/development/windows_support.md#clone-and-fetch-sources
on my system, running the ps1 file opens notepad whereas running the bat file works properly

ps1 -> bat

---

.github/workflows/test_hipcub.yml

Progress on https://github.com/ROCm/TheRock/issues/544.
Careless mistake from me, but forgot to enable hipcub tests even though they work...
Working [in this workflow](https://github.com/ROCm/TheRock/actions/runs/15143519981/job/42573683736)

[windows] Enable hipcub test.

---

external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/base/0001-Disable-hipSPARSE-and-CK-declarations-and-remove-ref.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0001-Rework-LoadHIP.cmake-to-be-based-purely-on-CMAKE_PRE.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0002-Generate-composable_kernel-ck-config.h-as-part-of-ma.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0003-TEMPORARY-Manually-disable-roctx-until-compatibility.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0004-enable-hipBLASLt-for-gfx-1102-1150-1151-1201.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0005-Add-gfx1150-gfx1151-to-hipblaslt-support-list-in-Bla.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0006-Support-gfx1151-in-aotriton.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0007-link-correct-version-of-hsa-runtime-with-c10_hip.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0008-rocm-clang-version-check-fix.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0009-Enable-torchvision-build-with-ROCm-on-Windows-147382.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0010-Include-AOTriton-dependent-sources-in-Windows-build-.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0011-Fix-HIP-Caffe2-Tests-152014.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0012-Enable-USE_ROCM-and-fix-assorted-issues.patch

Fixes https://github.com/ROCm/TheRock/issues/627 (in a better way this time).
This allows us to drop some CMake changes and still avoid linker errors.
Before this change we were carrying https://github.com/pytorch/pytorch/commit/3e78c9e967f154301937d4de1f5d9b4ab2cb5d84 but only applied to `aten/src/ATen/cuda/CUDABlas.cpp`, _not_ the HIPIFY'd `HIPBlas.cpp` that was generating linker errors when CK sources were not included. This might be a performance / functionality degradation, since what we had in TheRock actually _enabled_ the CK kernels that at least appeared to be "supported" (compiled / linked just fine), while that patch was _disabling_ them. I'll leave actually resolving that future work between CK and PyTorch maintainers.

[torch][windows] Move CK patch from 'hipified' to 'base'.

---

patches/amd-mainline/rocBLAS/0002-Find-rocm_smi-via-config-files.patch

Reintroduces a patch to find `rocm_smi` via `find_packages()`. The patch was reverted upstream with ROCm/rocBLAS@f8193e6 as it breaks the static build.

Bump rocBLAS 20250520

---

build_tools/github_actions/configure_ci.py

Currently, if HEAD is a doc change, our scheduled builds do not run like [this CI run](https://github.com/ROCm/TheRock/actions/runs/15127547635)
For scheduled runs, we always want to attempt to build!

[ci] Enabling schedule builds always

---

external-builds/pytorch/smoke-tests/pytorch_smoke_test.py
external-builds/pytorch/smoke-tests/run_smoke_tests.sh

The SKIPPED tests like below were considered as success since the shell script were running smoothly without any error.
This PR handles the SKIPPED cases as failure. 
```
external-builds/pytorch/smoke-tests/pytorch_smoke_tests.py::TestMatrixOperations::test_matrix_multiplication SKIPPED [ 10%]
external-builds/pytorch/smoke-tests/pytorch_smoke_tests.py::TestMatrixOperations::test_batch_matrix_multiplication SKIPPED [ 20%]
external-builds/pytorch/smoke-tests/pytorch_smoke_tests.py::TestMatrixOperations::test_matrix_multiplication_at_operator SKIPPED [ 30%]
external-builds/pytorch/smoke-tests/pytorch_smoke_tests.py::TestMatrixOperations::test_elementwise_multiplication SKIPPED [ 40%]
external-builds/pytorch/smoke-tests/pytorch_smoke_tests.py::TestMatrixOperations::test_transpose SKIPPED [ …
```

Check GPU availability to avoid unnecessary test skipping.

---

external-builds/pytorch/repo_management.py

See https://github.com/ROCm/TheRock/pull/531. This applies the same changes to the new `repo_management.py` script.

[torch] Set empty tags during torch checkout in new file.

---

.gitmodules

This switches the remaining math-libs
* hipCUB
* hipFFT
* hipRAND
* rocFFT
* rocRAND
to track `develop` and bumps the submodules, apart from hipFFT, for which `mainline` and `develop` are on par.

Bump and switch math-libs to track develop

---

patches/amd-mainline/hipBLASLt/0001-Guard-against-missing-directories-in-Tensile-Validat.patch

Fixes https://github.com/ROCm/TheRock/issues/683. Patch sent upstream here: https://github.com/ROCm/hipBLASLt/pull/2110.
We've had some users try building with a `C:\Program Files\AMD\ROCm` directory that has no `X.Y` directories (e.g. `C:\Program Files\AMD\ROCm\6.2`). Without a change like this, that produces errors during the build:
```
1.4	[129/234  27% :: 1.354] Creating Layer Norm, Softmax and Amax Assembly for gfx1100
1.4	FAILED: device-library/extops/L_256_4_1_gfx1100.s device-library/extops/L_256_4_0_gfx1100.s device-library/extops/S_8_32_gfx1100.s device-library/extops/S_16_16_gfx1100.s device-library/extops/S_4_64_gfx1100.s device-library/extops/S_2_128_gfx1100.s device-library/extops/S_1_256_gfx1100.s device-library/extops/A_S_S_256_4_gfx1100.s …
```

[windows] Apply patch for hipBLASLt path searching.

---

build_tools/patch_monorepo.py

This adds a script to apply patches from TheRock to the `rocm-libraries` monorepo, using a similar mechanism like `fetch_sources.py`.

Add script to apply patches to the monorepo

---

CMakeLists.txt
CMakePresets.json
README.md
cmake/therock_compiler_config.cmake
cmake/therock_global_post_subproject.cmake
cmake/therock_install_linux_build_id_files.cmake
cmake/therock_subproject.cmake

This does several things:
* Adds a CMake file to do some global system compiler setup and put the `CMAKE_MSVC_DEBUG_INFORMATION_FORMAT` from the README in there for Windows (this file was doing more and I've started this half a dozen times but never finished, so just going to land it now).
* Ensures that `-Wl,--build-id` is set on any binaries that we are doing debug symbol splitting from.
* Hardcodes CMP0087 (enabling generator expressions in install CODE) to NEW. Some of our very old projects need this and it unfortunately is a policy that must be set globally vs scoped.
* Adds a `{project_name}_BUILD_TYPE` override, allowing fine grained setting of build type per project. Used in our packaging preset to have the compiler build in Release vs RelWithDebInfo (which saves us some 600MB of …

Tune debug info configuration to work for package releases on Linux.

---

third-party/boost/CMakeLists.txt

Updates the boost tarball with files excluded that are causing trouble on Windows, reported in #684.

Update boost tarball

---

.github/workflows/build_linux_packages.yml
.github/workflows/build_windows_packages.yml

The save cache step is much slower than other post-build steps, particularly on Windows, where it can take upwards of 2 minutes. Reordering like this will ensure that we quickly upload logs and artifacts (which we always want) and later update the cache (which is only nice to have).

[ci] Move 'save cache' steps to the end of workflow files.

---

build_tools/linux_portable_build.py
external-builds/pytorch/build_prod_wheels.py

* One final script to rule them all for building production PyTorch wheels from released rocm-sdk wheels.
* This will be maintained in addition to any other developer-centric approaches to bootstrapping PyTorch and will track changes needed to build canonical production wheels from TheRock's rocm-sdk. Other approaches to building PyTorch are always possible.
* Written as a standalone script so that we can eventually upstream it to the pytorch repo proper in place of the existing ROCm build scripts.
* Still needs a bit more work to integrate the dep bundling from the original fat wheel script (for some system deps, no longer needed for ROCm deps, which are resolved at runtime from rocm-sdk wheels).
* While rocm-sdk wheels are not yet available on Windows, this script should be forward …

[torch] Add build_prod_wheels.py script.

---

external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0015-Preload-rocm-sdk-binaries-if-available.patch

* This is needed to enable rocm-sdk wheel based builds of PyTorch.
* See also #733.
Progress on #703.

[torch] Add patch 0015-Preload-rocm-sdk-binaries-if-available.

---

.github/workflows/build_linux_packages.yml
.github/workflows/build_windows_packages.yml

Archive creation is slow (https://github.com/ROCm/TheRock/issues/726), so I'd like to segment the jobs steps so we can see time measurements for each phase more easily.
If building both targets in the same command, we could overlap and exploit CPU parallelism. Not sure how much that practically helps though. Compression is CPU-bound and we don't want to oversubscribe.
Timing from the checks on this PR (sample size of 1): https://github.com/ROCm/TheRock/actions/runs/15311804950?pr=729
job | `therock-dist` time | `therock-archives` time
-- | --: | --:
Linux gfx94x | 1h 35m | 6m 50s
Linux gfx110x | 1h 50m | 4m 20s
Windows gfx110x | 50m | 1h 1m 30s
Timing after the compression level changes in https://github.com/ROCm/TheRock/pull/732:
job | `therock-dist` time | `therock-archives` time
-- | …

[ci] Split therock-dist and therock-archives into two job steps.

---

build_tools/fileset_tool.py
cmake/therock_artifacts.cmake

Progress on https://github.com/ROCm/TheRock/issues/726.
That issue has more data, but the most relevant experiment was generating `amd-llvm_dev_generic.tar.xz` on my dev machine with different compression settings:
preset | size | time | notes
-- | -- | -- | --
0 | 139.8 MB | 15.6 seconds |
1 | 123.9 MB | 17.6 seconds |
2 | 115.3 MB | 23.0 seconds | Proposal A
3 | 109.5 MB | 35.7 seconds | Proposal B
4 | 107.6 MB | 66.9 seconds |
5 | 98.24 MB | 107.2 seconds |
6 | 95.14 MB | 140.7 seconds | Default
7 | 91.75 MB | 158.7 seconds |
8 | 89.44 MB | 175.7 seconds |
9 | 87.47 MB | 183.7 seconds |
Timing before (https://github.com/ROCm/TheRock/actions/runs/15327687672):
job | `therock-dist` time | `therock-archives` time
-- | --: | --:
Linux gfx94x | 1h 35m | 6m 50s
Linux gfx110x | 1h 50m | 4m …

Reduce LZMA compression for faster therock-archives builds.

---

math-libs/CMakeLists.txt

Previously in the monorepo, running into an issue where `hipcub` was searching for a `rocprim` component, however since the `rocprim` version was ahead and `hipcub` was behind in our CMake, it was causing issues from [this monorepo run](https://github.com/ROCm/rocm-libraries/actions/runs/15304213808/job/43053064260) such as:
```
hipCUB] /__w/rocm-libraries/rocm-libraries/math-libs/hipCUB/hipcub/include/hipcub/backend/rocprim/util_type.hpp:786:32: error: no template named 'radix_key_codec' in namespace 'rocprim'
[hipCUB]   786 |     using key_codec = rocprim::radix_key_codec<T>;
[hipCUB]       |                       ~~~~~~~~~^
```
This [TheRock CI monorepo run](https://github.com/ROCm/rocm-libraries/actions/runs/15330308230/job/43135536362) proves it is working! and this will point to the …

[monorepo] Allow building hipCUB and rocThrust from the monorepo

---

CMakeLists.txt
profiler/CMakeLists.txt
profiler/rocprof-trace-decoder-binary/CMakeLists.txt

* Gated by THEROCK_ROCPROF_TRACE_DECODER_BINARY feature flag (default to ON on Linux).
* Fetches the manylinux release artifact and installs it into the dist tree.
* Adds a runtime dep to rocprofiler-sdk so the library goes anywhere it does. Note that `rocprofv3` dynamically loads the library if the `--att` argument is given. Otherwise, it is not implicated in the build.
Intended to stack on top of #752.
When both land, the following test does indeed emit att trace files: `./rocprofv3 --att -r -- ./hipblaslt-test`

[rocprof] Include binary-only advanced trace decoder in the build.

---

CMakeLists.txt
profiler/CMakeLists.txt
profiler/artifact-rocprofiler-sdk.toml

This was left out of the prior commit by accident.
The dogfooders I had testing this also attempted to use the feature group flags and had hiccups. This made me look at how things like THEROCK_ENABLE_PROFILER were setup, and I can't figure out what I was thinking when I wrote that, because it seems to do the opposite of what someone would want (i.e. disable all by default and then just enable what you want selectively). I converted these to regular options and had them default the THEROCK_ENABLE_ALL vs being locked to it.
Build command to test: `cmake -B build -GNinja . -DTHEROCK_AMDGPU_FAMILIES=gfx1100 -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DTHEROCK_ENABLE_ALL=OFF -DTHEROCK_ENABLE_PROFILER=ON`

[rocprof] Include trace decoder in the dist artifact.

---

.github/workflows/build_linux_pytorch_wheels.yml
.github/workflows/release_linux_pytorch_wheels.yml
external-builds/pytorch/build_prod_wheels.py

This PR eliminates target matrix from `release_linux_pytorch_wheels.yml` using `rocm-sdk` in `build_prod_wheels.py`
It uses `rocm-sdk targets` command to get the target.

Get target information using `rocm-sdk` in `build_prod_wheels.py`

---

ROADMAP.md

Based on a quick skim [ROCm Device wishlist](https://github.com/ROCm/ROCm/discussions/4276), folks seem to want RDNA2+. 
I've added some of each family (although I am not sure if we want to add all targets from [TheRock cmake](https://github.com/ROCm/TheRock/blob/main/cmake/therock_amdgpu_targets.cmake) )
I've also added `Build Passing` (could have better name?) category, as we have builds working for certain targets (but no tests working yet)

[docs] Adding more roadmap details

---

RELEASES.md

- Corrected example output for `which rocm-dsk` from `rocm-smi` to `rocm-sdk`
- Added punctuation for consistency
- Removed extra `the`

Fix typos in RELEASES.md

---

RELEASES.md

* Explain what a "release tarball" is
* Rework install instructions
* Show how to test an installation in a bit more detail
* Adjust section headings, pulling "Using Dockerfiles" out into its own section instead of burying it
I'm not touching the `install_rocm_from_artifacts.py` section yet... that's probably going to be most flexible and convenient but it needs some quality of life changes to the script that I'll want us to make together with docs changes.

Iterate on "installing from tarballs" documentation.

---

dockerfiles/cpubuilder/build_manylinux_x86_64.Dockerfile

Based on the website below, it is used the latest:
`sha256:634656edbdeb07f955667e645762ad218eefe25f0d185fef913221855d610456
`https://quay.io/repository/pypa/manylinux_2_28_x86_64?tab=tags

Update `manylinux_2_28_x86_64` image pin

---

.github/workflows/build_windows_packages.yml
.github/workflows/release_portable_linux_packages.yml
.github/workflows/release_windows_packages.yml

Fixes https://github.com/ROCm/TheRock/issues/542. More documentation (https://github.com/ROCm/TheRock/blob/main/RELEASES.md#installing-from-tarballs), script changes, and index pages for uploaded files would make these releases easier to use, but this at least gets tarballs building and uploading.
Tested here: https://github.com/ROCm/TheRock/actions/runs/15597803320. That produced https://therock-dev-tarball.s3.amazonaws.com/therock-dist-windows-gfx110X-dgpu-6.5.0.dev0%2B8fa909d3ab28e3c728d79334f6339a6ab933f787.tar.gz (4GB compressed, 20.5GB uncompressed), which I was able to extract then build PyTorch wheels with using:
```bash
cd TheRock\external-builds\pytorch
.\.venv\Scripts\activate.bat
set ROCM_HOME=D:/scratch/therock/therock-dist-windows-gfx110X-dgpu-6.5.0.dev0+8fa909d3ab28e3c728d79 …
```

[windows] Build nightly tarballs for Windows.

---

.github/workflows/release_windows_packages.yml
build_tools/github_actions/CMakeLists.txt
build_tools/github_actions/fetch_package_targets.py
build_tools/github_actions/tests/configure_ci_test.py
build_tools/github_actions/tests/fetch_package_targets_test.py

Progress on https://github.com/ROCm/TheRock/issues/542. The new Release Windows packages job failed last night: https://github.com/ROCm/TheRock/actions/runs/15633080737/job/44041709123
```
Run python ./build_tools/github_actions/fetch_package_targets.py
Traceback (most recent call last):
File "/home/runner/work/TheRock/TheRock/./build_tools/github_actions/fetch_package_targets.py", line 47, in <module>
main(args)
File "/home/runner/work/TheRock/TheRock/./build_tools/github_actions/fetch_package_targets.py", line 35, in main
family = info_for_key.get(package_platform).get("family")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```
That failed because some AMDGPU families in https://github.com/ROCm/TheRock/blob/main/build_tools/github_actions …

[windows] Fix fetch_package_targets without explicit AMDGPU_FAMILIES.

---

third-party/boost/cmake_project/CMakeLists.txt

Build stalls on Windows CI during boost build. Theory is build is stalling from contention by using all the cpu threads: `pbuild\third-party\boost\source\b2  -j 96 link=static ...`
(Found when troubleshooting with @ScottTodd and interactively inspecting the Windows runner tasklist in real time)

Limit boost b2 job arg to no more than 8

---

build_tools/_therock_utils/artifacts.py
build_tools/tests/artifacts_test.py

Splitting this change off from https://github.com/ROCm/TheRock/pull/772.
This will make it easier to work with artifacts that are on S3 and other non-local locations, where we'll have a URL and a filename, not a Path. We can also see about using [`cloudpathlib`](https://cloudpathlib.drivendata.org/stable/), "A Python library with classes that mimic `pathlib.Path`'s interface for URIs from different cloud storage services".

Add ArtifactName.from_filename util function.

---

RELEASES.md
docs/packaging/python_packaging.md

Progress on https://github.com/ROCm/TheRock/issues/703.
Tested that this installs a recent `rocm` wheel instead of `rocm-sdk`:
```bash
python -m pip install \
--index-url https://d2awnip2yjpvqn.cloudfront.net/v2/gfx110X-dgpu/ \
torch
```
I did _not_ test the wheels themselves (working on Windows today).

Refresh docs for `rocm` and `torch` pip installs.

---

build_tools/github_actions/build_linux_configure.py

This makes `extra_cmake_options` to convert flags to a list, in order for subprocess.run() to work properly.
Noticed failures in [rocm-libraries](https://github.com/ROCm/rocm-libraries/actions/runs/15688669189/job/44198245967?pr=156) where I pass in many cmake options
Added a `ref` to this branch, and it works in [rocm-libraries TheRock CI](https://github.com/ROCm/rocm-libraries/actions/runs/15689418446/job/44200737766?pr=156)

[ci] Adding list option for `extra_cmake_options`

---

third-party/sysdeps/linux/numactl/CMakeLists.txt

On systems with a newer version of autoconf the build fails because because aclocal 1.15 is expected. This patch runs autoreconf to regenerate the configuration for the version available on the system.
See: #712

[numactl] run autoreconf before configure

---

build_tools/fetch_artifacts.py

Splitting off more changes from https://github.com/ROCm/TheRock/pull/772.
I'm hoping to reuse this script for local rocm Python wheel building, particularly on Windows: https://github.com/ROCm/TheRock/issues/827, so I'll have a few more refactors coming soon. We should also be able to use the script on Linux after some workflow refactors here: https://github.com/ROCm/TheRock/blob/fc8767523fc639a17ba2fd9a5b5137eca334617f/.github/workflows/release_portable_linux_packages.yml#L136-L155
See also discussion on https://github.com/ROCm/TheRock/pull/779.

Rename --build-dir to --output-dir in fetch_artifacts.py.

---

experimental/rockbuilder/lib_python/repo_management.py

- Generate ninja build files instead of make build files on cmake configure
- Change build and install commands:
- "make -j<cpu_cnt>" to "cmake --build <build_dir>"
- "make install" --> "cmake --install <build_dir>
- fixes: https://github.com/ROCm/TheRock/issues/862

Use Ninja instead of make when building projects requiring cmake with Rockbuilder

---

CMakeLists.txt
build_tools/fetch_sources.py
ml-libs/CMakeLists.txt

Presently on win32, it is not even possible to reliably check out the composable_kernel repository. Disabling on windows for now.
Also adds the feature mapping plumbing and uses that to manage making it conditional deep in the project.
Should fix windows after the break in #876

[ck] Disable CK on win32.

---

ml-libs/CMakeLists.txt

* Drops copy/paste blas deps.
* Drops sqlite3 dep.
* Removes hardcoded CMAKE_BUILD_TYPE.
* Moves composable_kernel in MIOpen to a build dep vs runtime dep.

[ck] Trim deps to assumed minimum.

---

build_tools/packaging/python/templates/rocm/src/rocm_sdk/__main__.py
build_tools/packaging/python/templates/rocm/src/rocm_sdk/_devel.py

Progress on https://github.com/ROCm/TheRock/issues/827.
With this, I can build ROCm SDK wheels on Windows and run the `rocm-sdk path` subcommand:
```bash
python .\build_tools\linux_python_package.py \
--artifact-dir=D:\scratch\therock\artifacts_15685736080 \
--dest-dir=%HOME%\.therock\packages
pip install piprepo
piprepo build %HOME%/.therock/packages/dist
pip install rocm[libraries,devel]==0.1.dev0 \
--extra-index-url %HOME%/.therock/packages/dist/simple \
--force-reinstall --no-cache-dir
rocm-sdk path --cmake
```
Note that `rocm-sdk test` still fails since `rocm_sdk.find_libraries()` is not yet implemented. That's next on my list.
References:
* https://docs.python.org/3/library/fcntl.html
* https://docs.python.org/3/library/msvcrt.html
File locking APIs are quite different across Unix …

[windows] Add Windows support to rocm_sdk/_devel.py.

---

.github/workflows/test_hipcub.yml
.github/workflows/test_rocprim.yml
.github/workflows/test_rocthrust.yml
.github/workflows/test_sanity_check.yml

Previously, ctest had timeouts but sometimes it doesn't respect the timeouts. Now, adding GitHub level timeouts to respect the timeout

[ci] adding test timeouts per job level

---

docs/development/build_system.md
docs/development/git_chores.md

We've had more people asking how to work with submodules lately, so I figured I'd document the process as part of working on https://github.com/ROCm/TheRock/pull/887.

Add docs on adding a new submodule.

---

build_tools/export_source_archive.py

This script is intended to produce canonical source and prebuilt archives for the project, which are inputs to downstream native packaging flows (like DEB, RPM, etc).
As an example, this script can produce archives that serve the following roles:
* Used as a Debian `.orig.tar.gz` upstream source archive.
* Included in a RedHat SRPM.
* Archived on release pages to preserve exact released sources with everything included to build the project at a point in time.
While most vendors will choose to perform their own native build against pure source archives, we also support a mode where we generate "prebuilt source archives". These archives are structurally similar but include pre-built artifacts from a prior build system along with a skeleton of enough sources to re-assemble/package the …

Adds an `export_source_archive.py` script.

---

experimental/rockbuilder/README.md
experimental/rockbuilder/lib_python/project_builder.py
experimental/rockbuilder/rockbuilder.py

Add possibility to specify the directory where the produced (python wheel) files are copied after build. Like earlier, default value is "packages/wheels". This may be useful especially in the ci-builds.
Usage example:
./rockbuilder.py --project pytorch --output-dir test

Add output-dir parameter to rockbuilder

---

.github/workflows/test_hipblaslt.yml
.github/workflows/test_hipcub.yml
.github/workflows/test_rocblas.yml
.github/workflows/test_rocthrust.yml
.github/workflows/test_sanity_check.yml

Currently, other repos (like rocm-libraries) use TheRock's test workflows (since it's easily reusable and not much change happens)
In this [rocm-libraries TheRock CI workflow](https://github.com/ROCm/rocm-libraries/actions/runs/15788899766/job/44512015783?pr=324), it is incorrectly checking out the repo! Making this update so other repos can utilize all test workflows (rocprim is already enabled)

[ci] Adding correct repo checkout for reusable workflows

---

dockerfiles/cpubuilder/build_manylinux_x86_64.Dockerfile

The image used: https://quay.io/repository/pypa/manylinux_2_28_x86_64/manifest/sha256:d632b5e68ab39e59e128dcf0e59e438b26f122d7f2d45f3eea69ffd2877ab017
Generated local sha: 
https://github.com/ROCm/TheRock/actions/runs/15748697271
https://github.com/ROCm/TheRock/pkgs/container/therock_build_manylinux_x86_64/441871857?tag=users-erman-gurses-add-python-313
Tested:
https://github.com/ROCm/TheRock/actions/runs/15748807246
https://github.com/ROCm/TheRock/actions/runs/15748816208
https://github.com/ROCm/TheRock/actions/runs/15748811874
Tested locally with:
```
podman buildx build --file dockerfiles/cpubuilder/build_manylinux_x86_64.Dockerfile dockerfiles/cpubuilder
./build_tools/linux_portable_build.py --interactive --image "$imagehash" --docker=podman
cmake -S /therock/src -B …
```

Update `manylinux_x86_64` reference image sha

---

cmake/therock_amdgpu_targets.cmake

* This will enable building gfx1200/gfx1201 together (RX9060 and RX9070).
* Does not yet change test fanout.

Add gfx1200 target to the gfx120X-all family.

---

build_tools/packaging/python/templates/rocm/src/rocm_sdk/tests/core_test.py

Follow-up to https://github.com/ROCm/TheRock/pull/873, progress on https://github.com/ROCm/TheRock/issues/827.
I'm not sure why Linux has these `amd*` prefixed tool names but Windows does not. If we can unify that then subprojects won't need to jump through all these hoops to use the tools: https://github.com/ROCm/rocm-libraries/blob/6392fd0889abac24a8c7ba15a0ce95a982908635/projects/hipblaslt/tensilelite/Tensile/Toolchain/Validators.py#L116-L122
```python
class ToolchainDefaults(NamedTuple):
CXX_COMPILER = osSelect(linux="amdclang++", windows="clang++.exe")
C_COMPILER = osSelect(linux="amdclang", windows="clang.exe")
OFFLOAD_BUNDLER = osSelect(linux="clang-offload-bundler", windows="clang-offload-bundler.exe")
DEVICE_ENUMERATOR = osSelect(linux="rocm_agent_enumerator" if isRhel8() else …
```

[windows] Skip Linux-only aliases in console script tests.

---

build_tools/packaging/python/templates/rocm/src/rocm_sdk/_dist_info.py

Related to https://github.com/ROCm/TheRock/issues/703.
Up a few lines, the `get_py_package()` function takes `target_family` and calls `get_py_package_name(target_family)` itself, so it should not be passed a package name string. That might be safe if the `get_py_package_name(target_family)` function looked for a specific string pattern and was idempotent, but it is not.
This fixes `NOTE: Skipping libraries tests (not installed for this arch)` warnings running `rocm-sdk test` here: https://github.com/ROCm/TheRock/blob/195a3e395fdf56337450f42360249414c0cde0ae/build_tools/packaging/python/templates/rocm/src/rocm_sdk/__main__.py#L48-L53
I now see new errors with `rocm-sdk test` on Windows thanks to the fix (https://gist.github.com/ScottTodd/d7799ddbf86dc0458dd4a2a76b9ad1a1). I did _not_ test …

[python] Fix has_py_package() logic.

---

build_tools/github_actions/amdgpu_family_matrix.py

For the past 6 runs, 4 / 6 of them failed due to 9070 machines issues. To provide good signal, we will remove these test machines. We will look into machine issues (particularly, wifi slowness and HIP out of memory errors)

[ci] - Removing 9070 test machine

---

docs/packaging/python_packaging.md
external-builds/pytorch/README.md
external-builds/pytorch/build_prod_wheels.py

Progress on https://github.com/ROCm/TheRock/issues/827. These are the build script changes that I needed to build torch wheels on Windows after installing `rocm[libraries,devel]` wheels.
This will all get worked into the docs and integrated into CI/CD later... for now, here's what I'm working with:
1. Build the `rocm` wheels locally
```bash
python .\build_tools\linux_python_package.py \
--artifact-dir=D:/projects/TheRock/build/artifacts \
--dest-dir=%HOME%\.therock\packages
pip install piprepo
piprepo build %HOME%/.therock/packages/dist
pip install rocm[libraries,devel]==0.1.dev0 \
--extra-index-url %HOME%/.therock/packages/dist/simple \
--force-reinstall --no-cache-dir
```
2. With those `rocm` wheels, build pytorch:
```
python pytorch_torch_repo.py checkout --repo D:/b/pytorch
python …
```

[windows][torch] Add Windows support to build_prod_wheels.py.

---

build_tools/fetch_artifacts.py

I have more ideas for how to refactor here (see https://github.com/ROCm/TheRock/pull/772), but this is a reasonably non-invasive way to download all artifacts from a workflow run without affecting existing workflows that only want to download a subset.
A few things I'm grappling with on the design side here, which might warrant a new script that could replace this one:
* List available workflow runs, release builds, etc. (from S3 directories, an index page, or the github API?)
* Enumerate files available for a given run (artifacts archives, tarballs, python wheels)
* Filter files (based on target, category like "run" vs "test" vs "doc"), optionally tracking dependencies
* Download files (staging in temp dirs? caching?)
* Extract files (as needed), optionally deleting the originals if not …

Add --all mode to fetch_artifacts.py.

---

experimental/rockbuilder/CONFIG.md
experimental/rockbuilder/lib_python/project_builder.py
experimental/rockbuilder/projects/pytorch.cfg
experimental/rockbuilder/projects/pytorch_audio.cfg
experimental/rockbuilder/projects/pytorch_vision.cfg
experimental/rockbuilder/projects/rocm_sdk.cfg
experimental/rockbuilder/rockbuilder.py

- Move all the code from not belonging to functions to lower to same location in rockbuilder.py
- Set env variable ROCK_BUILDER_PACKAGE_OUTPUT_DIR for the execution time so that the project config files can use it if needed for saving the artifacts that are produced
- Check python env first before checking the rocm sdk location (helps future rockbuilder_config related changes)
- Refactor some of the code to use python Pathlib instead of string for referring to directories and files
- Allow "version" and "repo_url" in project.cfg files to be optional.  This allows to specify a simple project.cfg file for example just to install default application version with pip install command. Example:
```
--------------test_app.cfg ----
[project_info]
name=test_app
install_cmd = python -m pip install …
```

rockbuilder code cleanups

---

.github/workflows/build_linux_pytorch_wheels.yml
.github/workflows/release_linux_pytorch_wheels.yml

First revision to of the workflows used to build PyTorch packages. This is among other required to push builds to the dev bucket. Furthermore:
* Allows to point to a CloudFront URL different from the bucket. This enables consuming nightly ROCm packages but pushing torch wheels to a dev bucket.
* Sets defaults for `workflow_dispatch` to consume and build dev packages.

Revise workflows to build PyTorch wheels

---

experimental/rockbuilder/README.md
experimental/rockbuilder/lib_python/project_builder.py
experimental/rockbuilder/lib_python/repo_management.py
experimental/rockbuilder/rockbuilder.py

Add new "--src-dir" parameter to rockbuilder to specify the location where the project source
code is checked out. This may be needed in WIndows pytorch builds to ensure that the paths are short because otherwise the pytorch build commands can easily
exceed the 8191 characters maximum length that can be used on Windows command prompt.
1) If --src-dir parameter is used to checkout multiple source files, the parameter is used to specify the base-directory under each projects source code is checked out.
Example: ./rockbuilder.py --checkout --src-dir src_prj
In this case there would be following type of source directories: src_prj/pytorch and src_prj/pytorch_vision
2) If --src-dir parameter is instead used while checking out source code only for a single project, it is assumed that the …

Add new src_dir parameter to rockbuilder

---

build_tools/third_party/s3_management/update_dependencies.py

Following up on https://github.com/ROCm/TheRock/pull/934#issuecomment-3020832059.
Once we run this script with these changes, our index pages like https://d2awnip2yjpvqn.cloudfront.net/v2/gfx1151/ will include Windows wheels too, for example alongside:
```
Links for numpy
numpy-2.3.0-cp311-cp311-manylinux_2_28_x86_64.whl
numpy-2.3.0-cp312-cp312-manylinux_2_28_x86_64.whl
numpy-2.3.0-cp313-cp313-manylinux_2_28_x86_64.whl
```

Include win_amd64 packages in python indices.

---

.github/workflows/release_windows_packages.yml
build_tools/_therock_utils/py_packaging.py
requirements.txt

Progress on https://github.com/ROCm/TheRock/issues/827. This builds ROCm SDK Python wheels on Windows and publishes them to our release S3 buckets so the instructions at https://github.com/ROCm/TheRock/blob/main/RELEASES.md#installing-releases-using-pip should work on Windows after the scheduled nightly jobs run.
> [!NOTE]
> Tested here: https://github.com/ROCm/TheRock/actions/runs/15962567326 . I've also tested with artifacts downloaded instead of built from source over on my fork at https://github.com/ScottTodd/TheRock/actions/runs/15934220838.
>
> Tested installing and using a bit here: https://gist.github.com/ScottTodd/4f2532324e02613ed0366f764f77df56
I've tried to keep this workflow similar to [`.github/workflows/release_portable_linux_packages.yml`](https://github.com/ROCm/TheRock/bl …

[windows][python] Publish rocm wheels in release_windows_packages.yml.

---

docs/packaging/python_packaging.md
external-builds/pytorch/README.md
external-builds/pytorch/build_prod_wheels.py
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0016-Move-rocm_sdk-preload-ahead-of-DLL-loading-add-amd_c.patch

Fixes https://github.com/ROCm/TheRock/issues/708. Progress on https://github.com/ROCm/TheRock/issues/827. Relates to https://github.com/ROCm/TheRock/issues/703.
This reworks our PyTorch source build instructions to only use the [`external-builds/pytorch/build_prod_wheels.py`](https://github.com/ROCm/TheRock/blob/main/external-builds/pytorch/build_prod_wheels.py) script, for both Linux and Windows. Support on Windows is recent, thanks to https://github.com/ROCm/TheRock/pull/914 and https://github.com/ROCm/TheRock/pull/940.

[torch] Update docs for running build_prod_wheels.py.

---

external-builds/pytorch/.gitignore
external-builds/pytorch/build_prod_wheels.py
external-builds/pytorch/pytorch_torch_repo.py
external-builds/pytorch/pytorch_triton_repo.py
external-builds/pytorch/repo_management.py

* Merely adds scripting support for checking out the proper pinned repository and building if done.
* Should be NFC on any existing build pipelines until enabled.
* The build procedure is a bit annoying because it relies on a couple of action at a distance build flags and pins that need to line up exactly.
As part of this, I did a code review of what the Triton build is doing behind the scenes, some of which is problematic. I have looped the Triton maintainer in and we will fix in followups:
* The AMD backend has bugs in terms of how it is finding the libamdhip64.so having to do with it using dlopen to probe existing loaded libraries by barename (i.e. `libamdhip64.so`) vs soname (i.e. `libamdhip64.so.6`), resulting in some exotic fallbacks to scanning process tables that should not be …

[pytorch] Add build support for the vendored pytorch-triton-rocm wheel.

---

CMakeLists.txt
ml-libs/CMakeLists.txt
patches/amd-mainline/MIOpen/0001-Disable-conv_wino_fury_RxS-for-gfx115x.patch
patches/amd-mainline/MIOpen/0002-Fix-no-ck-build-3852.patch

Building MIOpen with CK enabled fails for other GPU targets when linking. Disabling using CK in MIOpen if a non-supported target is in the THEROCK_AMDGPU_TARGETS list.

Disable using CK in MIOpen if target is not gfx9{08,0a,42,50}

---

.github/workflows/build_linux_pytorch_wheels.yml
external-builds/pytorch/build_prod_wheels.py

Partially tested at https://github.com/ROCm/TheRock/actions/runs/16005755463 (that failed since the dev bucket does not currently have rocm wheels)
This was broken by both https://github.com/ROCm/TheRock/pull/942 and https://github.com/ROCm/TheRock/pull/948. See full logs on https://github.com/ROCm/TheRock/actions/runs/15988444502.
* Changes to argparse made it so that arguments were moved to subcommands instead of being top level. We could also revert those changes, but I like having the subcommand (`build` or `install-rocm`) be the first part argument, instead of in the middle
* The new `get_installed_package_version` function had an invalid `\` character in an f-string.

[torch] Fix build_prod_wheels argparse and version checking.

---

.github/workflows/build_windows_packages.yml
.github/workflows/release_windows_packages.yml

There are issues in the wild with the latest release on Windows: https://github.com/ninja-build/ninja/issues/2616. We had compilation errors in another project building LLVM: https://github.com/iree-org/iree/pull/21208. Thankfully we've dodged those issues here, but I'd feel safer if we pinned to a version that did not have known issues on Windows.

[ci][windows] Pin ninja version in Windows workflows.

---

build_tools/bump_submodules.py

MIOpen requires a compatible version of composable_kernel whose commit hash is specified in MIOpen's requirements file.

Pin composable_kernel by default

---

.github/workflows/build_linux_packages.yml
.github/workflows/build_linux_pytorch_wheels.yml
.github/workflows/release_linux_pytorch_wheels.yml
.github/workflows/release_portable_linux_packages.yml
build_tools/linux_portable_build.py
docs/environment_setup_guide.md

The used image: https://quay.io/repository/pypa/manylinux_2_28_x86_64/manifest/sha256:634656edbdeb07f955667e645762ad218eefe25f0d185fef913221855d610456
Used local SHA: https://github.com/ROCm/TheRock/pkgs/container/therock_build_manylinux_x86_64/451416019?tag=main

Add updated image sha for manylinux_x86_64

---

experimental/rockbuilder/README.md
experimental/rockbuilder/lib_python/project_builder.py
experimental/rockbuilder/rockbuilder.py

Add option for the <project_name>-version parameter to rockbuilder
Allow specifying the project versions as an optional parameters  to override the version specified in the project.cfg file:
Example:
./rockbuilder.py --pytorch-version=v2.7.1 --pytorch_audio-version=v2.7.1  --checkout

Add option to override the default project version with a --<project_name>-version parameter in rockbuilder

---

docs/packaging/python_packaging.md
external-builds/pytorch/README.md
external-builds/pytorch/build_prod_wheels.py
external-builds/pytorch/pytorch_triton_repo.py

* Includes a couple of workarounds that are unfortunate but would be hard to patch/fix at the root in one step:
* Some of the environment variables needed to locate ROCm for the PyTorch build (which shouldn't be necessary at all but c'est la vie for now) conflict badly with the clang driver heuristics for locating device bitcode. Workaround is to also manually set the `HIP_DEVICE_LIB_PATH` and curse at the stars about removing all of these legacy special vars.
* PyTorch at head uses rocm-smi-lib for distributed, and including those headers does not advertise the transitive include dirs for the sysdeps, which causes us to not find libdrm (presumably most old ROCm installs treated that as a system library, whereas we vendor it and need to propagate its header path through find_package). …

[pytorch] Extend build_prod_wheels.py to build pytorch nightly.

---

cmake/therock_artifacts.cmake

* An artifact name needs to start with a letter.
* Any following character must be an alphanumeric character or a dash.
This helps to avoid #935 on the CMake side.

Error on illegal artifact names

---

docs/development/windows_support.md

Fixes https://github.com/ROCm/TheRock/issues/513. Progress on https://github.com/ROCm/TheRock/issues/36.
* DLLs are available for tests _in the dist folder_
* HIPIFY ninja patch was dropped
* "No shared libraries" is no longer useful to include in the table... I think
* Added Composable Kernel and mxDataGenerator as unsupported

[windows][docs] Refresh windows_support.md table.

---

.github/workflows/test_pytorch_wheels.yml
external-builds/pytorch/pytorch_audio_repo.py
external-builds/pytorch/pytorch_torch_repo.py
external-builds/pytorch/pytorch_vision_repo.py
external-builds/pytorch/run_linux_pytorch_tests.sh
external-builds/pytorch/setup_venv.sh

* Moves venv creation to `setup_venv.sh`, it should not be handled in `run_linux_pytorch_tests.sh`.
* Do not longer install packages in `run_linux_pytorch_tests.py` as these are installed in `setup_venv.sh`.
* Cleans up the description in `pytorch_torch_repo.py`.
* Moves environment variables.
* Modifies the workflow and script to install a specific torch version.

Rework `test_pytorch_wheels` workflow

---

build_tools/github_actions/amdgpu_family_matrix.py

Deactivating tests as the sanity test is failing with
```
FileNotFoundError: [Errno 2] No such file or directory: './hipcc_check'
..
FAILED tests/test_rocm_sanity.py::TestROCmSanity::test_hip_printf - FileNotFoundError: [Errno 2] No such file or directory: './hipcc_check'
```

Deactivate post-submit tests on gfx950

---

external-builds/pytorch/build_prod_wheels.py

Progress on https://github.com/ROCm/TheRock/issues/827.
Follow-up to https://github.com/ROCm/TheRock/pull/959, expanding support on Windows.
Without this I get a warning from `build_prod_wheels.py` on Windows:
```
cmake -GNinja -DBUILD_PYTHON=True -DBUILD_TEST=False -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=D:\b\pytorch_v2.7.0\torch -DCMAKE_PREFIX_PATH=D:\projects\TheRock\external-builds\pytorch\.venv\Lib\site-packages;D:\projects\TheRock\external-builds\pytorch\.venv\Lib\site-packages\_rocm_sdk_devel\lib\cmake -DPython_EXECUTABLE=D:\projects\TheRock\external-builds\pytorch\.venv\Scripts\python.exe -DTORCH_BUILD_VERSION=2.7.0a0+rocmsdk20250709 -DUSE_FLASH_ATTENTION=0 -DUSE_GLOO=OFF -DUSE_KINETO=OFF -DUSE_MEM_EFF_ATTENTION=0 -DUSE_NUMPY=True -DUSE_ROCM=ON D:\b\pytorch_v2.7.0
cmake …
```

[torch][windows] Set hip_device_lib_path on Windows.

---

build_tools/packaging/python/templates/rocm/src/rocm_sdk/tests/libraries_test.py

Progress on https://github.com/ROCm/TheRock/issues/827 (see also the specific bug report at https://github.com/ROCm/TheRock/issues/827#issuecomment-3028742585).
Previously, `rocm-sdk test` failed on my dev machine with errors like `FileNotFoundError: Could not find module 'D:\scratch\therock\python_rocm_2\.venv\Lib\site-packages\_rocm_sdk_libraries_gfx110X_dgpu\bin\hipfft.dll' (or one of its dependencies). Try using the full path with constructor syntax.`
<details><summary>Expand for full logs</summary>
<p>
```
(.venv) λ rocm-sdk test
testCLI (rocm_sdk.tests.base_test.ROCmBaseTest.testCLI) ... ++ Exec [D:\scratch\therock\python_rocm_2]$ 'D:\scratch\therock\python_rocm_2\.venv\Scripts\python.exe' -P -m rocm_sdk --help
ok
testTargets (rocm_sdk.tests.base_test.ROCmBaseTest.testTargets) ... …
```

[windows] Preload compiler DLLs in ROCmLibrariesTest.

---

.github/workflows/build_windows_pytorch_wheels.yml
.github/workflows/release_windows_packages.yml
.github/workflows/release_windows_pytorch_wheels.yml
external-builds/pytorch/README.md
external-builds/pytorch/build_prod_wheels.py

Progress on https://github.com/ROCm/TheRock/issues/827 (!!)
Tested at https://github.com/ROCm/TheRock/actions/runs/16185309410, which triggered these:
* https://github.com/ROCm/TheRock/actions/runs/16186383600 (gfx1151)
* https://github.com/ROCm/TheRock/actions/runs/16186941663 (gfx120X-all)
* https://github.com/ROCm/TheRock/actions/runs/16186966931 (gfx110X-dgpu)
Some next steps after this, roughly in order:
* Monitor scheduled jobs to check that wheels are successfully built and uploaded
* Download/install and test the wheels on various systems, exercising components like hipBLASLt
* Update support status:
* https://github.com/ROCm/TheRock?tab=readme-ov-file#support-status
* https://github.com/ROCm/TheRock/blob/main/RELEASES.md#python-packages-support-status
* Build torchvision and …

[torch][windows] Build Windows release PyTorch wheels.

---

.github/workflows/build_linux_pytorch_wheels.yml
.github/workflows/release_linux_pytorch_wheels.yml
.github/workflows/test_pytorch_wheels.yml
build_tools/github_actions/CMakeLists.txt
build_tools/github_actions/python_to_cp_version.py
build_tools/github_actions/tests/python_to_cp_version_test.py
external-builds/pytorch/skipped_tests.py

This wires up testing the PyTorch wheels build in the `build_linux_pytorch_wheels` workflow. The package version to test is grabbed from the package name after building it and passed to the next job. This could probably made more robust by moving it to a script but should be acceptable for now. At the moment tests get only triggered for the platforms that are also used to test TheRock nightlies, which for now only is gfx942.
Furthermore, this adds another PyTorch test to the skip tests (here `test_index_add_correctness`), which fails with `AssertionError: Tensor-likes are not close!` on gfx942 using Python 3.11 but passes for 3.12 and 3.13.

Wire up testing PyTorch wheels

---

build_tools/github_actions/amdgpu_family_matrix.py
tests/test_rocm_sanity.py

hipcc test was failing for gfx950 due to hipcc coming from `opt/rocm` (`cwd` didn't work, `hipcc` pulled it from /opt/rocm, silly mistake from me and slipped through the cracks)
Now, it works for gfx950 and also for windows tests! Also adding extra logging
Tested [in CI test workflow](https://github.com/ROCm/TheRock/actions/runs/16206539664)

[ci] - Enabling gfx950 tests

---

build_tools/_therock_utils/py_packaging.py

On some clusters, various LD_LIBRARY_PATH based approaches have been used to create isolated ROCm installations. Since the default RUNPATH based approach allows LD_LIBRARY_PATH to override, this can cause resolution of libraries from alternate locations without intending to. Switching to the older "RPATH" allows us to create the hermetic Python wheels as intended.
Tested: Built python wheels from local artifacts, installed, used `readelf -d` to verify proper RPATH vs RUNPATH tags, ran executables.
Fixes #1011

When embedding libraries in Python wheels, force use of RPATH.

---

build_tools/_therock_utils/py_packaging.py

This fixes the release build failures noted here: https://github.com/ROCm/TheRock/pull/1012#discussion_r2207896570. Linux can use RPATH to connect libraries from different packages while Windows relies on DLLs being either co-located, discoverable on the PATH, or already being loaded.
Tested locally:
```bash
cmake --build ./build --target therock-archives
python .\build_tools\build_python_packages.py --artifact-dir=.\build\artifacts --dest-dir=.\build\packages --version=7.0.0.dev0
pip install piprepo
piprepo build ./build/packages/dist
pip install rocm[libraries,devel]==7.0.0.dev0 --extra-index-url .\build\packages\dist\simple
rocm-sdk test
```

[Windows] Skip rpath branches during packaging.

---

external-builds/pytorch/README.md
external-builds/pytorch/pytorch_audio_repo.py
external-builds/pytorch/pytorch_torch_repo.py
external-builds/pytorch/pytorch_triton_repo.py
external-builds/pytorch/pytorch_vision_repo.py
external-builds/pytorch/repo_management.py

This enables us to build off of the ROCm/pytorch release/2.7 branch, enabling 2.7.1 on ROCm 7.
jeffdaily and I cherry-picked the couple of missing patches from HEAD to make this configuration work with TheRock.
When building with the pre-built aotriton, it hits against #1025.
Should be NFC for all other builds.
Progress on #1026.

Extend pytorch build to work with our official 2.7 backport.

---

external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/base/0001-Disable-hipSPARSE-and-CK-declarations-and-remove-ref.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/base/0002-Backport-Remove-use-of-warpsize-on-host-side-compila.patch
external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/base/0002-ROCm-Backport-Remove-use-of-warpsize-on-host-side-co.patch
external-builds/pytorch/repo_management.py

Fixes https://github.com/ROCm/TheRock/issues/1048.
This backports https://github.com/pytorch/pytorch/commit/04bd7e6850e8efec77994963ffee87549555b9c3 onto our 2.7.0 patches to accommodate the breaking changes in https://github.com/ROCm/clr/commit/54503f0d677df44d1a17a8e66f0c60a4e000393f. The commit did not apply cleanly with a regular cherry-pick and needed to be applied _before_ running HIPIFY, so I made these changes manually (which was quite painful). We can't sustain this style of backporting patches so need to make progress on https://github.com/ROCm/TheRock/issues/1039 and using https://github.com/ROCm/pytorch/ soon.
Tested locally on Windows:
```bash
python -m pip install --index-url https://d2awnip2yjpvqn.cloudfront.net/v2/gfx110X-dgpu/ rocm[libraries,devel] --upgrade
python …
```

[torch] Backport warpsize patch to 2.7.0 to fix release builds.

---

patches/amd-mainline/rocSOLVER/0001-Allow-rocblas_DIR-env-var-to-be-unset-on-Windows.patch

This resolves the errors building on Windows reported at https://github.com/ROCm/TheRock/pull/345#issuecomment-3076258917.
I also sent this patch for review upstream at https://github.com/ROCm/rocSOLVER/pull/990.

[Windows] Apply rocblas_DIR env var patch to rocSOLVER.

---

math-libs/BLAS/CMakeLists.txt
math-libs/BLAS/artifact-blas.toml
patches/amd-mainline/rocSOLVER/0001-Allow-rocblas_DIR-env-var-to-be-unset-on-Windows.patch
third-party/fmt/pre_hook_therock-fmt.cmake

This enables building rocSOLVER clients which requires to build fmt with PIC enabled.
Closes #236

Enable building rocSOLVER clients

---

cmake/therock_amdgpu_targets.cmake

This excludes to build hipBLASLt for which tensilelite isn't fully supported, as outlined in #1062.

Exclude hipBLASLt for non-supported targets

---

build_tools/packaging/python/templates/rocm/src/rocm_sdk/tests/core_test.py

When the locale on Windows is set to Japanese or other non-English, Python will fail to decode the output text.
Here we use the `locale.getpreferredencoding` to get the correct encoding.
Fixes #1074.

Use ``getpreferredencoding`` to decode the text from subprocess

---

build_tools/github_actions/configure_ci.py
build_tools/github_actions/configure_target_run.py
build_tools/github_actions/determine_version.py
build_tools/github_actions/fetch_job_status.py
build_tools/github_actions/fetch_package_targets.py
build_tools/github_actions/fetch_test_configurations.py
build_tools/github_actions/github_actions_utils.py
build_tools/github_actions/python_to_cp_version.py
build_tools/github_actions/upload_build_summary.py

This moves all code that deals with `GITHUB_OUTPUT`, `GITHUB_ENV`, `GITHUB_PATH`, and `GITHUB_STEP_SUMMARY` to a common utility file. Now we won't be tempted to continue copy/pasting utils or import functions that aren't intended to be exported like
```python
from configure_ci import set_github_output
```
I thought about writing some unit tests for the new file... we could look to https://github.com/saadmk11/github-action-utils/blob/main/tests/test_github_action_utils.py for inspiration.

Introduce github_actions_utils.py to share common functions.

---

.github/workflows/build_portable_linux_pytorch_wheels.yml
.github/workflows/build_windows_pytorch_wheels.yml
build_tools/github_actions/configure_target_run.py

Progress on https://github.com/ROCm/TheRock/issues/589.
Incomplete test runs were triggered at
* https://github.com/ROCm/TheRock/actions/runs/16424062043
* https://github.com/ROCm/TheRock/actions/runs/16426198049
* https://github.com/ROCm/TheRock/actions/runs/16427212517
(still need an easy way to build and test "dev" pytorch packages using "nightly" rocm packages)

[ci][windows][torch] Adapt configure_target_run for Windows testing.

---

external-builds/pytorch/repo_management.py

Split the git base patch apply for pytorch to be perormed on two stages.
First apply base patches to main repository and then do the git submodule checkout.
After that apply the base-patches to git submodules.
This will enable us to patch the revision of submodule checked out.

Pytorch allow patching which submodule rev is checked out

---

.github/workflows/build_windows_pytorch_wheels.yml
external-builds/pytorch/README.md
external-builds/pytorch/patches/pytorch_audio/v2.7.0/pytorch_audio/base/0001-Allow-clang-cl-as-the-C-CXX-compiler-on-Windows.patch

Progress on https://github.com/ROCm/TheRock/issues/910.
Tested at https://github.com/ROCm/TheRock/actions/runs/16429221525 (build only) and locally, with a sanity check:
```bash
$ pip freeze
```
```python
>>> import torchaudio
>>> print(torchaudio.__version__)
2.7.0a0+rocmsdk20250721
```
For the patch, pytorch_audio had been forcing the compiler to `cl`, while we've been building with `clang-cl` for base pytorch. Trying to build with `cl` fails due to (at least) these clang-specific flags that get set with `USE_ROCM`: https://github.com/pytorch/pytorch/blob/cab28330f8c49cdb66d6a299755dc09c87c14a9d/cmake/Dependencies.cmake#L1028-L1041
```cmake
list(APPEND HIP_CXX_FLAGS -Wno-shift-count-negative)
list(APPEND HIP_CXX_FLAGS -Wno-shift-count-overflow)
list(APPEND HIP_CXX_FLAGS …
```

[torch][windows] Enable pytorch_audio build on Windows.

---

RELEASES.md

The previous docs required users to scroll up, copy rocm instructions, then replace `rocm[libraries,devel]` with `torch`. Now they can just copy/paste the `torch` instructions directly.

[doc] Expand installation instructions for torch wheels.

---

docs/development/windows_support.md

I just found another instance where `file(TO_CMAKE_PATH "$ENV{HIP_PATH}" HIP_PATH)` is needed, so copying notes from https://github.com/ROCm/TheRock/issues/827#issuecomment-3032949792 into source control. This gives us/me a place to look for common issues and their fixes.

[doc] Add Windows platform support tips.

---

.github/workflows/build_portable_linux_pytorch_wheels.yml
.github/workflows/build_windows_pytorch_wheels.yml
build_tools/github_actions/write_torch_version.py

Splitting this off from https://github.com/ROCm/TheRock/pull/1100.
Not tested recently.

[torch] Replace inline bash with write_torch_version.py.

---

.github/workflows/test_packages.yml
build_tools/github_actions/test_executable_scripts/test_hipblaslt.py

Ran a test with [failing CI run ID](https://github.com/ROCm/TheRock/actions/runs/16485423682/job/46611899777) and ran a new [CI test run](https://github.com/ROCm/TheRock/actions/runs/16506892410), works!
Linked issue #1114

[ci] - Exclude one hipblaslt test for windows gfx1151

---

external-builds/pytorch/patches/pytorch/main/pytorch/hipified/0001-Enable-USE_ROCM-disable-USE_RCCL-on-Windows.patch
external-builds/pytorch/patches/pytorch/main/pytorch/hipified/0002-Fix-LoadHIP-handling-of-environment-variable-paths-o.patch
external-builds/pytorch/patches/pytorch/main/pytorch/hipified/0003-Revert-copying-hipblaslt-and-rocblas-dirs-on-Windows.patch
external-builds/pytorch/patches/pytorch/main/pytorch/hipified/0004-Patch-ifdef-for-__builtin_clz-on-Windows.patch

This copies a patch from our `v2.7.0` patches folder (https://github.com/ROCm/TheRock/blob/main/external-builds/pytorch/patches/pytorch/v2.7.0/pytorch/hipified/0013-Patch-ifdef-for-__builtin_clz-on-Windows.patch) to the `main` folder
It is expected to fix errors like https://github.com/ROCm/TheRock/actions/runs/16569646709/job/46858176812:
```
2025-07-28T13:46:04.8652913Z [7099/7147] Building CXX object functorch\CMakeFiles\functorch.dir\csrc\dim\dim.cpp.obj
2025-07-28T13:46:04.8653325Z FAILED: functorch/CMakeFiles/functorch.dir/csrc/dim/dim.cpp.obj 
2025-07-28T13:46:04.8662076Z C:\home\runner\_work\_tool\Python\3.11.9\x64\Lib\site-packages\_rocm_sdk_devel\lib\llvm\bin\clang-cl.exe  /nologo -TP -DEXPORT_AOTI_FUNCTIONS -DFUNCTORCH_BUILD_MAIN_LIB -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS …
```

[torch] Apply patch for __builtin_clz on Windows.

---

external-builds/pytorch/build_prod_wheels.py

The `pytorch-triton-rocm` package is build now on a nightly cadence as will get overwritten as long as the package version is not updated. While upstream includes a git hash in the version extra, this is not the case for the ROCm/trition version currently tracked and build alongside to PyTorch 2.7 from ROCm/pytorch.

Append ROCm version to trition version suffix

---

external-builds/pytorch/skipped_tests.py

Test is failing as reported in #1143. Skipping for now.

Skip `test_float32_matmul_precision_get_set`

---

.github/workflows/build_portable_linux_pytorch_wheels.yml
.github/workflows/test_pytorch_wheels.yml

With commit c2ac13f, sources to build PyTorch get pulled from ROCm/PyTorch but this is not the case when testing the wheels afterwards. The patch makes sure that the same repo / branch is used for testing as for the builds before.

Pass PyTorch version to checkout the correct repo

---

.github/workflows/test_pytorch_wheels.yml
build_tools/github_actions/amdgpu_family_matrix.py
build_tools/github_actions/populate_redshift_db.py

The OSSCI cluster is losing a bunch of mi300 capacity and getting more mi325 capacity for the time being. Hence moving the self-hosted runner usage from mi300 to mi325.

Replace mi300 self-hosted runner in OSSCI with mi325

---

external-builds/pytorch/skipped_tests.py

Test is failing as reported in #1151. Skipping for now.

Skip `test_graph_concurrent_replay`

---

build_tools/hack/build_env_diag.py

Progress on https://github.com/ROCm/TheRock/issues/762.
Add Python3 diagnosis Python script to `build_tools/hack`
By adding a build environment diagnosis script to detects build environment for Users(wants to build by source) or CI/CD.
Contributed with @ScottTodd from pwsh(PowerShell) initial design moving to py script.
Several tests on native Windows machine and WSL2 environment, not tested in CI/CD env
This script maybe buggy in initial design

Add build environment diagnose script

---

core/CMakeLists.txt

Latest dump: https://github.com/ROCm/amdgpu-windows-interop/tree/main/20250722a
See https://github.com/ROCm/TheRock/blob/main/docs/development/windows_support.md#building-clr-from-partial-sources for information about this submodule.
Full release notes and commit history would be great... but we don't have that yet. The main thing we're looking forward to in this update is expanded support for navi44 (gfx1200).

[windows] Bump amdgpu-windows-interop to version 20250722.

---

math-libs/BLAS/CMakeLists.txt
math-libs/support/CMakeLists.txt

Enables to build hipBLASLt from a patched `rocm-libraries` superrepo with `-DTHEROCK_USE_EXTERNAL_ROCM_LIBRARIES=ON` and `-DTHEROCK_ROCM_LIBRARIES_SOURCE_DIR` pointing to the superrepo.

Enable building hipBLASLt from superrepo

---

.github/workflows/build_linux_jax_wheels.yml
build_tools/third_party/s3_management/manage.py
build_tools/third_party/s3_management/update_dependencies.py

Adds a workflow for building JAX with release tarballs

Add workflow for JAX wheel builds

---

patches/amd-mainline/rocPRIM/0002-Correct-GTest-print-check-for-128-bit-ints-on-Window.patch

Bumps the individual submodules to HEAD, ignoring the pinned Tensile and CK submodules. Further, cherry-picks a patch from an upstream PR to unbreak rocPRIM on Windows (will be dropped once merged upstream and submodule bumped).

Bump rocm-libraries submodules 20250804

---

.github/workflows/build_windows_pytorch_wheels.yml
external-builds/pytorch/README.md
external-builds/pytorch/build_prod_wheels.py

Progress on https://github.com/ROCm/TheRock/issues/910.
Tested at https://github.com/ROCm/TheRock/actions/runs/16728414496/job/47354811134. I'm still having trouble building locally though.

[torch] Enable torchvision in Windows releases.

---

external-builds/pytorch/repo_management.py

Reverts ROCm/TheRock#1092
This breaks 'base' patches by incorrectly applying the `THEROCK_UPSTREAM_DIFFBASE` tag, see https://github.com/ROCm/TheRock/pull/1092#discussion_r2226039819.
When I run what should be a no-op:
```
python pytorch_torch_repo.py checkout
python pytorch_torch_repo.py save-patches
```
instead I get this diff, which deletes all the 'base/' patches: https://github.com/ScottTodd/TheRock/commit/7718788aafcf7423b014ef2066d212abe0da439f.
We could also fix forward, but I haven't received a response on the PR after 2 weeks and this has bit me a few times since reporting the issue.

Revert "Pytorch allow patching which submodule rev is checked out"

---

external-builds/pytorch/build_prod_wheels.py

The https://github.com/ROCm/pytorch/tree/release/2.7 branch is now pinning to `cmake==4.0.3` (see https://github.com/ROCm/pytorch/pull/2444), so this is a conflicting requirement that causes our builds to fail:
```
Ignoring numpy: markers 'python_version == "3.9"' don't match your environment
Requirement already satisfied: cmake<4 in /opt/python/cp312-cp312/lib/python3.12/site-packages (3.31.6)
Collecting astunparse==1.6.3 (from -r /__w/TheRock/TheRock/external-builds/pytorch/pytorch/requirements.txt (line 2))
Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
ERROR: Cannot install cmake<4 and cmake==4.0.3 because these package versions have conflicting dependencies.
The conflict is caused by:
The user requested cmake<4
The user requested cmake==4.0.3
To fix this you …
```

Unpin CMake from pytorch build_prod_wheels.py.

---

patches/amd-mainline/clr/0005-Explicitly-load-libamdhip64.so.7.patch

While hipcc adds linker flag to link `libamdhip64.so.7`, clr was still loading `libamdhip64.so`. This adds a patch to explicitly load `libamdhip64.so.7`.
Closes #1180.

Patch clr to load `libamdhip64.so.7`

---

.github/workflows/release_portable_linux_packages.yml

Workflow was failing with
```
Run benc-uk/workflow-dispatch@e2e5e9a103e331dad343f381a29e654aea3cf8fc
🏃 Workflow Dispatch Action v1.2.4
Error: Expected double-quoted property name in JSON at position 151
```

Fix syntax error

---

external-builds/pytorch/build_prod_wheels.py
external-builds/pytorch/patches/pytorch/main/pytorch/hipified/0001-Enable-USE_ROCM-disable-USE_RCCL-on-Windows.patch
external-builds/pytorch/patches/pytorch/main/pytorch/hipified/0002-Fix-LoadHIP-handling-of-environment-variable-paths-o.patch
external-builds/pytorch/patches/pytorch/main/pytorch/hipified/0003-Revert-copying-hipblaslt-and-rocblas-dirs-on-Windows.patch
external-builds/pytorch/patches/pytorch/main/pytorch/hipified/0004-ROCm-Windows-Include-native_transformers-srcs-to-fix.patch
external-builds/pytorch/patches/pytorch/main/pytorch/hipified/0005-Support-FLASH_ATTENTION-MEM_EFF_ATTENTION-via.-aotri.patch

Windows nightly PyTorch builds are currently broken: https://github.com/ROCm/TheRock/actions/workflows/release_windows_pytorch_wheels.yml?query=branch%3Amain. This fixes them.
Builds without `--enable-pytorch-flash-attention-windows` were failing with `error: use of undeclared identifier 'mha_fwd_aot'`, but we also needed to remove the `exclude(ATen_HIP_SRCS` code that was added upstream to resolve `lld-link: error: undefined symbol ... transform_bias_rescale_qkv_cuda`.
This is a minimal fix-forward for the first issue and restructures the patches for the second issue.
Context:
* https://github.com/ROCm/TheRock/pull/1207#discussion_r2267878623
* https://github.com/pytorch/pytorch/pull/152951#discussion_r2267714825
Built locally with `python build_prod_wheels.py build --pytorch-dir …

[torch][windows] Rebase aotriton patches, fix undeclared `mha_fwd_aot`.

---

CMakeLists.txt
build_tools/fileset_tool.py
build_tools/tests/fileset_tool_test.py
cmake/therock_artifacts.cmake
cmake/therock_default_targets.cmake
cmake/therock_global_post_subproject.cmake
cmake/therock_subproject.cmake
docs/development/development_guide.md

The motivation of this change is to enable the following developer productivity features:
* Development in a sub-project `build` directory should cause the super-project to see the sub-project as out of date and take appropriate action. This is done by injecting an ALL `therock-touch` target into each sub-project so that `ninja` will invalidate the super-project stage-install state, causing a re-install and rebuild of dependents.
* One stop commands to build and distribute in a sub-project without switching back and forth. Users can now just run `ninja therock-dist` in any sub-project to build and distribute their local changes (i.e. to `build/dist/rocm`, etc).
* More coverage of `expunge` targets, making sure that project state can be reset more completely.
Key changes:
* Removes some …

Improve ergonomics of using TheRock as a development driver for sub-projects.

---

cmake/therock_amdgpu_targets.cmake

This unbreaks building gfx90X-dcgpu and gfc110X-dgpu: https://github.com/ROCm/TheRock/actions/runs/16965000210/

Exclude building CK for unsupported targets

---

build_tools/packaging/python/templates/rocm-sdk-devel/MANIFEST.in

If a compressed tarball is included, this is compressed using XZ-format and not the GNU compression utilities:
https://github.com/ROCm/TheRock/blob/bc413b64743a961841bcb056dce1758d85429798/build_tools/_therock_utils/py_packaging.py#L427-L428

Fix rocm-sdk-devel's manifest

---

build_tools/fetch_artifacts.py
build_tools/install_rocm_from_artifacts.py

This was part of a larger change to enable bootstrapping a build from artifacts but breaking out separately as it is self contained.
Also makes several bug fixes and quality of life improvements:
* If the output dir does not exist, it is created (vs exiting with a success code).
* Added arguments for filtering artifacts by include/exclude patterns.
* Prior to extraction, deletes the artifact directory if it exists (avoids possibility of incorrect combinations and failures to extract read only files).
* Fixes the .tar.xz stem determination logic to work for any number of extensions.
* Adds an argument to delete the archives after extraction (true by default) as this is the most common case.
* Exits with a failure code if artifacts are not found in the bucket.
* Prints a summary at the …

Rework fetch_artifacts.py to do parallel extraction.

---

dockerfiles/build_manylinux_x86_64.Dockerfile
dockerfiles/install_vcpkg.sh

Adds vcpkg to the Dockerfile to use it for installing OpenMPI until it is added to TheRock.

Add vcpkg and OpenMPI

---

external-builds/pytorch/patches/pytorch/main/pytorch/hipified/0001-Include-native_transformers-srcs-to-fix-link-errors.patch
external-builds/pytorch/patches/pytorch/main/pytorch/hipified/0002-Support-FLASH_ATTENTION-MEM_EFF_ATTENTION-via.-aotri.patch
external-builds/pytorch/patches/pytorch/main/pytorch/hipified/0003-Revert-inductor-Windows-inductor-use-intel-openmp.-1.patch

Progress on https://github.com/ROCm/TheRock/issues/1257 and https://github.com/ROCm/TheRock/issues/1261 and expected to fix errors like on
* https://github.com/ROCm/TheRock/actions/runs/17069813390/job/48400376426#step:6:64
`ERROR: Could not find a version that satisfies the requirement intel-cmplr-lib-ur==2025.1.1 (from intel-openmp) (from versions: none)`
* https://github.com/ROCm/TheRock/actions/runs/16965353747/job/48092417765#step:6:53
`ERROR: Could not find a version that satisfies the requirement intel-openmp==2025.1.1; platform_system == "Windows" (from torch) (from versions: none)`
The upstream PR https://github.com/pytorch/pytorch/pull/160258 is under consideration to be reverted or reworked but the fix-forward PR https://github.com/pytorch/pytorch/pull/160976 is not yet …

[torch] Revert intel-openmp dependency change.

---

.github/workflows/build_jax_dockerfile.yml
.github/workflows/test_jax_dockerfile.yml

Add a workflow file that will build a JAX docker image and run the JAX unit tests.
Will run this after it's merged, and then make another PR that fills in the workflow.

Add stub workflow for running JAX tests

---

build_tools/build_python_packages.py
build_tools/buildctl.py
build_tools/packaging/python/templates/rocm-sdk-core/setup.py
build_tools/packaging/python/templates/rocm-sdk-core/src/rocm_sdk_core/_cli.py
build_tools/packaging/python/templates/rocm/src/rocm_sdk/tests/core_test.py
docs/development/windows_support.md
docs/packaging/python_packaging.md

Fixes https://github.com/ROCm/TheRock/issues/600, follow-up to https://github.com/ROCm/TheRock/pull/1216.
* Include hipInfo artifacts during Python wheel generation
* Add console script entry point for hipInfo
* Add console script test case (not checking any output since the test can run on a system with no GPU)
* Expanded on docs for how to use the output of `build_tools/build_python_packages.py`
* Minor fix for `build_tools/buildctl.py` on Windows, which I used for testing (more docs to come on that)
Separately I looked at https://github.com/ROCm/TheRock/blob/main/patches/amd-mainline/rocm-libraries/0018-Revert-remove-options-no-enumerate-966.patch to see if we can drop that patch now that we build `hipInfo`. See https://github.com/ROCm/TheRock/pull/1281 for that.
Built Python packages …

[windows] Add hipInfo to Python packages and improve docs.

---

build_tools/third_party/s3_management/update_dependencies.py

Follow up to commit 1040aab which reverted the upstream change locally until the dependency on intel-openmp is resolved upstream.

Remove `intel-openmp` from dependencies

---

.github/workflows/test_jax_dockerfile.yml

Context: https://github.com/ROCm/TheRock/pull/1277#discussion_r2288768088
> There are syntax errors in this file, so the workflow is failing to parse and is trying to run: https://github.com/ROCm/TheRock/actions/workflows/test_jax_dockerfile.yml
> 
> https://github.com/ROCm/TheRock/actions/runs/17104558085
> 
> ```
>  Invalid workflow file: .github/workflows/test_jax_dockerfile.yml#L1
> (Line: 28, Col: 9): Required property is missing: type, (Line: 31, Col: 9): Required property is missing: type
> ```

Fix syntax errors in test_jax_dockerfile.yml.

---

external-builds/pytorch/README.md

Filling in more details about how to interface with our PyTorch build infrastructure:
* Added a support table showing which versions we build for using what code
* Clarified testing instructions
* Elaborated on how patches are applied and how to save patches
* Explain the patch directory structure
TODO (follow-up changes):
* Delete old patch directories and change default `--patchset` and `--repo-hashtag` values
* Switch Linux and Windows to both use `nightly` instead of one using `main` and the other using `nightly`?

[torch][docs] Document supported versions and patch management.

---

build_tools/third_party/s3_management/manage.py

`S3.Bucket.objects.filter()` can only return up to 1,000 objects in a bucket. This refactors to create an iterator that will paginate through repsonses from `S3.Client.list_objects_v2()`, see [1].
Furthermore, the way `KEEP_TRESHOLD` was applied resulted in dropping "random" packages once the threshold was has been exceeded. This removes the threshold (in favor of applying a server side retention policy later) and also drops to skip packages between a specific date range as this function was unused.
Resolves #1302.
Note: `ListObjects` has been revised and it is recommend to use the newer `ListObjectsV2` instead [2].
[1] https://boto3.amazonaws.com/v1/documentation/api/latest/guide/paginators.html
[2] https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html

Use paginator and remove `KEEP_TRESHOLD`

---

.github/workflows/release_windows_packages.yml

Follow-up to https://github.com/ROCm/TheRock/pull/887 where this was missed. The project is now included in its own submodule, no extra checkout needed.

Drop amdgpu-windows-interop checkout from release_windows_packages.yml.

---

build_tools/github_actions/amdgpu_family_matrix.py
build_tools/github_actions/configure_ci.py
build_tools/github_actions/tests/configure_ci_test.py

Progress on https://github.com/ROCm/TheRock/issues/1337. Related to https://github.com/ROCm/TheRock/issues/1097.
gfx90X-dcgpu and gfx101X-dgpu builds have been passing on nightly runs on https://github.com/ROCm/TheRock/actions/workflows/ci_nightly.yml?query=branch%3Amain
This allows us to separate the _policy decision_ "what support level is a given gfx family" from the _technical reality_ "does that gfx family pass builds/tests". Now we can have the nightly job include gfx families that are passing builds/tests instead of only having "xfail" jobs there.
While I was renaming the matrix variables I also did related refactoring to hopefully make this code easier to maintain going forward.
* Ran `python .\build_tools\github_actions\tests\configure_ci_test.py` locally
* Confirm which targets …

[ci] Rename xfail matrix to nightly, mark 90x and 101x as passing.

---

CMakeLists.txt
README.md

See https://github.com/ROCm/TheRock/issues/1347.
The CMake configure warning looks like this in context:
```
[cmake] -- Configuring background job pool for 6 concurrent jobs
[cmake] CMake Warning at CMakeLists.txt:35 (message):
[cmake]   *************************************************
[cmake] 
[cmake]   Windows builds are currently unstable during the migration to rocm-systems!
[cmake]   Builds are expected to succeed but there are runtime errors and timeouts.
[cmake]   The last known good commit on Windows is
[cmake]   https://github.com/ROCm/TheRock/commit/529fa36d69c7d4295317a70d3c5c88000a364b2c
[cmake]   See https://github.com/ROCm/TheRock/issues/1347 for details.
[cmake] 
[cmake]   *************************************************
[cmake] 
[cmake] 
[cmake] -- Enabling building …
```

Warn about unstable Windows builds while broken by the rocm-systems migration.

---

.github/workflows/release_portable_linux_packages.yml
.github/workflows/release_portable_linux_pytorch_wheels.yml

Add inputs added for build_portable_linux_pytorch_wheels.yml from #1110 
Added required inputs for both the release_portable_linux_packages(Which runs build_portable_linux_pytorch_wheels.yml) and also release_portable_linux_pytorch_wheels.

Adding attributes to release workflows

---

patches/amd-mainline/rocm-systems/0010-Revert-SWDEV-547108-Fix-compilation-errors-under-Win.patch
patches/amd-mainline/rocm-systems/0011-Revert-formatting-changes-to-palblitcl.cpp.patch

Progress on https://github.com/ROCm/TheRock/issues/1347.
1. Patch 10 is a revert of https://github.com/ROCm/rocm-systems/commit/72b9408fedb08da67d0f3fec89316fb6e44153f2, with conflicts manually resolved. Something in that change causes programs (including many of our math-libs tests) to hang. A fix-forward is also up for review at https://github.com/ROCm/rocm-systems/pull/809.
2. Patch 11 is essentially a cherry-pick of https://github.com/ROCm/rocm-systems/pull/802. This commit https://github.com/ROCm/rocm-systems/commit/2ff2316227dc3bb04447060c719e78baf2d7383f ran clang-format on https://github.com/ROCm/rocm-systems/blob/develop/projects/clr/rocclr/device/pal/palblitcl.cpp, resulting in this broken file: [`palblitcl.cpp` @ df11d9dc](https://github.com/ROCm/rocm-systems/blob/df11d9dcc21dcd …

Fix Windows on new rocm-systems with some revert patches.

---

CMakeLists.txt

Removes the warning introduced with commit 1901eab as builds were fixed with commit 21700cd. Keeps a commented out and templated version of the warning message to re-add more easily if needed in the future.

Remove warning about unstable Windows builds

---

README.md

Removes the warning introduced with commit 1901eab also from the README as builds have been fixed with commit 21700cd.

Remove warning about unstable builds from README

---

.github/workflows/release_portable_linux_packages.yml
.github/workflows/release_windows_packages.yml
.github/workflows/test_pytorch_wheels.yml
RELEASES.md
build_tools/setup_venv.py
external-builds/pytorch/README.md
external-builds/pytorch/build_prod_wheels.py

Replaces `d2awnip2yjpvqn.cloudfront.net` with `rocm.nightlies.amd.com` which redirects to the CloudFront distribution.

Introduce `rocm.nightlies.amd.com`

---

patches/amd-mainline/rocm-libraries/0023-Run-gentest.py-with-python-on-Windows-across-_parse_.patch

> [!NOTE]
> Also sent upstream as https://github.com/ROCm/rocm-libraries/pull/1443
Progress on https://github.com/ROCm/rocm-libraries/issues/535. Seeing if this fixes our rocblas tests that have been failing on WIndows like https://github.com/ROCm/TheRock/actions/runs/17438210230/job/49520134395
```
INFO:root:++ Exec [C:\runner\_work\TheRock\TheRock]$ ./build/bin/rocblas-test --yaml ./build/bin/rocblas_smoke.yaml
rocBLAS info: client (OPENMP) reduced omp_set_num_threads to 10
rocBLAS info: Using reference library 'OpenBLAS::OpenBLAS'
rocBLAS warning: Reference library may not support 64-bit input arguments. If running a test suite, please use --gtest_filter=-*stress* to avoid 64-bit test failures.
rocBLAS version: 5.1.0.3eb64eb743
rocBLAS-commit-hash: …
```

Apply gentest.py patch to fix rocblas testing on CI.

---

RELEASES.md

Follow-up to https://github.com/ROCm/TheRock/pull/1328. That has helped a lot, but a few people have still been confused by which families include which specific targets and supported devices.

[doc] Make gfx targets for each release family more explicit.

---

.github/workflows/build_windows_packages.yml
.github/workflows/ci.yml
.github/workflows/ci_windows.yml

a test fail job working here: https://github.com/ROCm/TheRock/actions/runs/17470521668/job/49617493256

[ci] adding `expect_failure` for windows CI nightly

---

CONTRIBUTING.md

* Added "communication channels" section with a link to the AMD Developer Community Discord Server (also linked from https://www.amd.com/en/developer.html)
* Document https://pre-commit.com/ requirement and setup example
* Document branch naming recommendations (similar to https://github.com/ROCm/rocm-systems/blob/develop/CONTRIBUTING.md#1-branch-naming-and-forks)
* Misc grammar/style tweaks

[doc] Refresh CONTRIBUTING.md (comms channels, pre-commit, branch naming, etc.).

---

external-builds/pytorch/build_prod_wheels.py

Progress on https://github.com/ROCm/TheRock/issues/1040, getting closer to enabling aotriton in PyTorch on Windows.
This will supersede https://github.com/ROCm/TheRock/pull/1409 and is dependent on https://github.com/pytorch/pytorch/pull/162330.
The UTF8 change I believe helps with warnings about logs for copying files with unicode characters in their names:
```
Message: '%s %s -> %s'
Arguments: ('copying', 'torch\\lib\\aotriton.images\\amd-gfx11xx\\flash\\bwd_kernel_dq\\FONLY__\uff0afp32@16_48_0_T_T_1___gfx11xx.aks2', 'build\\lib.win-amd64-cpython-312\\torch\\lib\\aotriton.images\\amd-gfx11xx\\flash\\bwd_kernel_dq')
--- Logging error ---
Traceback (most recent call last):
File "C:\Users\Nod-Shark16\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1163, in emit …
```

[torch] Adjust env vars used for builds with aotriton enabled.

---

.github/workflows/build_portable_linux_pytorch_wheels.yml
.github/workflows/build_windows_pytorch_wheels.yml
.github/workflows/release_windows_packages.yml
.github/workflows/release_windows_pytorch_wheels.yml
build_tools/github_actions/promote_wheels_based_on_policy.py
build_tools/github_actions/python_to_cp_version.py
external-builds/pytorch/README.md

Raising this PR to add the changes we added for Pytorch Gating in Linux through #1110 
Also added the staging bucket mechanism added for Linux builds
Below are the steps we want integrated as part of windows builds too:
Build PyTorch wheels
Upload the built wheels to the v2-staging (staging bucket)
Run PyTorch tests using wheels from the staging bucket
Only if tests pass, copy the validated wheels from the staging bucket to the release bucket
If no runner is available: Promotion is blocked by default. Set bypass_tests_for_releases=true only for exceptional cases under amdgpu_family_matrix.py

Windows Pytorch builds gating with tests

---

RELEASES.md

As [reported on Discord](https://discord.com/channels/1239631572886491286/1370146945867448431/1413223080662269983), Zsh can't copy/paste commands with unescaped square brackets. Guidance from https://stackoverflow.com/a/30239714 is to use quotes, which also helps for Windows Powershell.
Tried the commands on Windows (cmd.exe), they still work.

[doc] Wrap `rocm[libraries,devel]` in quotes for Zsh and powershell.

---

.github/workflows/release_windows_packages.yml

We stopped publishing Linux packages to GitHub releases in https://github.com/ROCm/TheRock/pull/1016, but this comment in the Windows workflow was leftover.

Drop comment about uploading Windows packages to to GitHub releases.

---

.github/workflows/build_portable_linux_pytorch_wheels.yml
.github/workflows/build_windows_pytorch_wheels.yml

See https://github.com/ROCm/TheRock/issues/827 and https://github.com/ROCm/TheRock/issues/910.
We weren't running the [`external-builds/pytorch/sanity_check_wheel.py`](https://github.com/ROCm/TheRock/blob/main/external-builds/pytorch/sanity_check_wheel.py) script on Windows since we weren't building torchaudio and torchvision. Now that we are, we can run this sanity check script.
Ran the sanity check script locally on Windows after building. I have _not_ tested the workflows.
Truncated output (I've rebuilt many times):
```
λ python .\sanity_check_wheel.py C:\Users\Nod-Shark16\.therock\pytorch
Valid wheel: torch-2.7.0a0+rocmsdk20250624-cp312-cp312-win_amd64.whl (182538029 bytes)
Valid wheel: torch-2.7.0a0+rocmsdk20250716-cp312-cp312-win_amd64.whl (183473493 bytes)
...
Valid wheel: …
```

[torch] Run sanity_check_wheel.py in build_windows_pytorch_wheels.yml

---

cmake/therock_subproject_dep_provider.cmake
patches/amd-mainline/llvm-project/0001-Enable-MSVC-support-in-comgr.patch
patches/amd-mainline/llvm-project/0002-hipcc-fix-default-include-path-on-Windows-and-adapt-.patch
patches/amd-mainline/llvm-project/0003-HACK-Handle-ROCM-installation-layout-of-lib-llvm-bin.patch
patches/amd-mainline/llvm-project/0004-Disable-hipcc-passing-hip-device-libs.patch
patches/amd-mainline/llvm-project/0005-Ensure-to-use-libamdhip64-with-major-version.patch
patches/amd-mainline/llvm-project/0006-Rework-constructHipPath-so-HIP_PATH-env-var-is-lower.patch
patches/amd-mainline/llvm-project/0007-Policy-CMP0053-is-no-longer-supported-by-CMake-4-151.patch
patches/amd-mainline/llvm-project/0008-offload-Tunnel-CMAKE_PREFIX_PATH-with-proper-escapin.patch

Previously, we were manually setting the PKG_CONFIG_PATH environment variable at configure time, but this cannot be reliably propagated to sub-configures that are invoked at build time (as is done for the LLVM runtimes).
This patch switches to adding these prefixes to the CMAKE_PREFIX_PATH, which is the standard way of chaining between top-level and nested configure invocations. It requires a bit of path munging since the CMake pkg-config macros expect to get a prefix, not the fully nested path to the files (which is what the env var expects).
Also inlines a patch to LLVM which fixes an escaping bug for tunneling CMAKE_PREFIX_PATH when it contains more than one entry. I will upstream this to LLVM next week.
Fixes #1481

Reworks pkg-config handling so that it is based on CMAKE_PREFIX_PATH.

---

build_tools/hack/env_check/check_tools.py
docs/environment_setup_guide.md

Update the documentation and check_tools.py to reflect the now possible usage of cmake 4 under Linux, while still requiring cmake 3 for Windows.
Related: Issue #318 and PR #1440

Update documentation/tools to reflect cmake 4 support on Linux

---

README.md

https://github.com/ROCm/TheRock/pull/1283 probably meant to link to https://github.com/ROCm/TheRock/issues/1284 instead of 128

Fix issue link in README.md

---

third-party/sysdeps/linux/libdrm/CMakeLists.txt

cmake build was failing because `libdrm` man pages requires `docutils` for generation, but we don't include `docutils` in our `requirements.txt`.
```
[therock-libdrm] ModuleNotFoundError: No module named 'docutils'
[therock-libdrm] ninja: build stopped: subcommand failed.
ninja: build stopped: subcommand failed.
```
Since we don't include these man pages in TheRock distribution anyway, it's best to disable their creation in the first place.
Update `CMakeLists.txt` for `libdrm` to disable generation of man pages.
Verify cmake builds successfully.
It builds successfully
- [ X] Look over the contributing guidelines at https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.

Turn off generation of libdrm man pages

---

.github/workflows/release_windows_packages.yml

Progress on https://github.com/ROCm/TheRock/issues/1072. More follow-up to https://github.com/ROCm/TheRock/pull/1382 for missed plumbing due to workflows being copy/pasted instead of reusing the same scripts.
This workflow run failed: https://github.com/ROCm/TheRock/actions/runs/17788093970/job/50562946451#step:6:35, since it was looking outside of the staging subdirectory:
```
++ Exec [C:\runner\_work\TheRock\TheRock]$ 'C:\runner\_work\TheRock\TheRock\.venv\Scripts\python.exe' -m pip install --index-url=https://rocm.nightlies.amd.com/gfx1151 torch==2.10.0a0+rocm7.0.0rc20250917
Looking in indexes: https://rocm.nightlies.amd.com/gfx1151
ERROR: Could not find a version that satisfies the requirement torch==2.10.0a0+rocm7.0.0rc20250917 (from versions: none)
```
The workflow that triggered it …

Set SG_STAGING_SUBDIR in Windows release workflow.

---

dockerfiles/build_manylinux_x86_64.Dockerfile

Bumping the CMake version of the manylinux image used by the CI to match PyTorch's minimum CMake version 3.27. This is required since commit: https://github.com/pytorch/pytorch/commit/c2beeadeb40e927c51bc5bcd409b3f28374a5190
The change is a requirement when building PyTorch nightly wheels.
This should be considered to be the new default policy for our CMake progression for the manylinux image to match the PyTorch CMake progression (if it is higher than ours).

Bump CMake version to 3.27 in manylinux image to match PyTorch's

---

.github/workflows/build_linux_packages.yml
.github/workflows/build_windows_packages.yml

Enable ninja `-k 0` to keep going through errors.

---

build_tools/github_actions/fetch_test_configurations.py

It seems the `hipblaslt` tests seem to average around 20mins, sometimes going beyond 30 mins. This results in a timeout error like below:
- https://github.com/ROCm/TheRock/actions/runs/17587709994/job/49967842476
- https://github.com/ROCm/TheRock/actions/runs/17587709994/job/49967842476
I actually don't know why the actual runtime was so close to timeout, but regardless, extending timeout to resolve this error

[ci] Extending timeout for hipblaslt tests

---

external-builds/pytorch/build_prod_wheels.py

Fixes https://github.com/ROCm/TheRock/issues/1309, where `import torch` would require `libomp140.x86_64.dll` from an install of Visual Studio.
See the comments and the linked issue.
This seems to solve the issue on a technical level. I'm wondering
1. Should we prefer Intel OpenMP over MSVC OpenMP? Installing and using it is more of a hassle
2. Should we disable OpenMP instead of go through this effort?
3. If we do bundle MSVC OpenMP, are there any licensing implications? Other random dlls get bundled too 🤔 
The implementation here was inspired by https://github.com/pytorch/pytorch/pull/158922, but I had more success using the `VCToolsRedistDir` environment variable set by the MSVC developer command prompt than using `vswhere`. The specific path that is found on my system is `C:\Program …

[torch][windows] Copy libomp140.x86_64.dll to torch/lib.

---

build_tools/github_actions/cleanup_processes.ps1

Get a more accurate and reliable read on whether orphaned processes were cleaned up successfully. Follow up to https://github.com/ROCm/TheRock/pull/1361 and https://github.com/ROCm/TheRock/pull/1521
Additionally since the script does exit with an appropriate exit code based on success or failure, it would cause the test job to fail early if processes could not be stopped.
Logs from earlier tests would end with `Failed to stop executable(s)` so it was unknown whether the processes stopped, along with the `exited: True` as seen here:
https://github.com/ROCm/TheRock/pull/1518#issuecomment-3305499637
The polling method was suggested in discussions here:
https://github.com/ROCm/TheRock/pull/1518#issuecomment-3308689749
Also prioritizing the use of WMI since it seems to work more effectively: …

[CI] Poll process status in Pre/Post test job cleanup

---

build_tools/fetch_artifacts.py
build_tools/install_rocm_from_artifacts.py

Realizing that `install_rocm_from_artifacts.py` installs everything (after some updates to `fetch_artifacts.py`), like here: https://github.com/ROCm/TheRock/actions/runs/17944455280/job/51030783105
In order to save CI time, I'm enabling the component flags for `install_rocm_from_artifacts.py`

[ci] Enable component flags for `install_rocm_from_artifacts.py`

---

.github/workflows/test_component.yml
.github/workflows/test_packages.yml
build_tools/github_actions/fetch_test_configurations.py
build_tools/github_actions/test_executable_scripts/test_hipblaslt.py
build_tools/github_actions/test_executable_scripts/test_hipsparse.py
build_tools/github_actions/test_executable_scripts/test_miopen.py
build_tools/github_actions/test_executable_scripts/test_rocsparse.py

Testing for TheRock CI has become longer and longer, resulting in long queues and long waits.
After some testing with pytest-xdist, gtest conversion to ctest and gtest-parallel, all three options resulted in incredibly slower times than the current gtest implementation.
After some testing, I figured out gtest sharding for GitHub action runners. Here's a [test run](https://github.com/ROCm/TheRock/actions/runs/17841452228) which ran tests in 53mins in total!
Currently, only gtest executables are able to be sharded. However, the gtest executables are the most costly in time, so it works out!
Changes:
- gtest executables with extensive times (that are worth sharded) are sharded into around 15min chunks based on historic CI run data. (ex: miopen takes 1h 20m for mi325, it's now 14mins avg …

[ci] Adding gtest sharding

---

build_tools/install_rocm_from_artifacts.py

Some changes I made while working on https://github.com/ROCm/TheRock/issues/1559. I tried to use this script via [`.github/actions/setup_test_environment/action.yml`](https://github.com/ROCm/TheRock/blob/main/.github/actions/setup_test_environment/action.yml) but I ended up using [`build_tools/fetch_artifacts.py`](https://github.com/ROCm/TheRock/blob/main/build_tools/fetch_artifacts.py) instead.
Changes:
* Add more logging
* Add more type hints
* Reflow comments
* Mkdir with parents=True

[ci] Misc improvements to install_rocm_from_artifacts.py.

---

.github/workflows/release_portable_linux_packages.yml
.github/workflows/release_windows_packages.yml

We sometimes cancel jobs to free up CI resources. In those cases we don't typically want to spend a few minutes uploading partial caches from cancelled builds.

Skip cache uploads if jobs are cancelled.

---

README.md

Improving the flow of reading the instructions by introducing some more cross references

Small clarification of documentation for devs that build from source

---

build_tools/github_actions/test_executable_scripts/test_hipblaslt.py

#1114 is fixed! 
Working here: https://github.com/ROCm/TheRock/actions/runs/18023622950
Removing exclude logic as no longer needed for hipBLASLt. The tests still run into an occasional GPU hang but that is a separate and known issue

[ci] Enable disabled hipBLASLt tests 

---

third-party/sysdeps/common/zlib/CMakeLists.txt
third-party/sysdeps/common/zlib/patch_install.py
third-party/sysdeps/common/zlib/patch_source.sh
third-party/sysdeps/common/zstd/CMakeLists.txt
third-party/sysdeps/common/zstd/patch_install.sh
third-party/sysdeps/common/zstd/patch_source.sh

The renamed and patchelf edited libraries in ROCk artifacts are not providing the symbol version tag. This was resulting in rpm package installation failure.
Patch will create the library with the updated name. Patchelf editing is not required.
librocm_sysdeps_z and librocm_sysdeps_zstd libraries will be created as part of  zlib and zstd builds
The patchelf edited libraries are not providing the symbol version tag
Rather than editing libraries to update soname , create libraries with the updated name by editing the target name in source code
Verified the elfdeps provides field of the libraries.
Required symbol version tags are provided by the libraries

SWDEV-555589 - Edit zlib and zstd source code to create libraries with updated name

---

.github/workflows/build_portable_linux_python_packages.yml
.github/workflows/build_windows_python_packages.yml
build_tools/fetch_artifacts.py
build_tools/github_actions/fetch_job_status.py
build_tools/github_actions/github_actions_utils.py
build_tools/github_actions/tests/github_actions_utils_test.py
build_tools/tests/fetch_artifacts_test.py
docs/development/github_actions_debugging.md

Progress on https://github.com/ROCm/TheRock/issues/1559.
This follows up on https://github.com/ROCm/TheRock/pull/1596, allowing for workflow runs in forks to download artifacts from workflow runs in this shared repository and then build their packages on standard github-hosted runners. I previously tested that way but by hacking these scripts.
This allows us to separate "where we download artifacts from" and "where we upload artifacts to". In pipelined workflows these are typically the same locations but in developer testing workflows it is useful to download from common artifacts and then not upload at all.
I had to refactor `fetch_artifacts.py` a bit so the new settings would get stored and applied consistently across the file. I used a new `BucketMetadata` dataclass for that.
I also …

Generalize bucket info to better support artifact fetching from forks.

---

build_tools/packaging/linux/build_package.py
build_tools/packaging/linux/packaging_utils.py

Replaced hardcoded or relative path handling with Path(__file__).resolve().parent 
This improves portability and ensures correct path resolution regardless of the current working directory
Relative paths were used and invoking the scripts from a different directory was failing
Makes the script location-independent by using Python pathlib expression
Invoke the script from different paths and test the functionality
Invoking from different paths is also working as expected

Use Python pathlib to find the directory containing the current script.

---

external-builds/pytorch/README.md
external-builds/pytorch/build_prod_wheels.py

Linux PyTorch builds are failing due to:
1. FBGEMM_GENAI: CMake errors when enabled.
2. AOTriton / Flash Attention: Requires `liblzma` (via `xz` and `xz-devel`), causing build failures.
* Disable FBGEMM_GENAI by default.
* Disable Flash Attention (AOTriton) on Linux by default (`USE_FLASH_ATTENTION=0`).
* Plan to bundle `xz`/`xz-devel` with TheRock in future updates to resolve the Triton dependency.
These changes unblock Linux PyTorch builds while upstream issues are addressed.
#1408

Disable FBGEMM_GENAI and Flash Attention (AOTriton) by Default in Linux Torch Builds

---

build_tools/github_actions/write_torch_versions.py

write_torch_version.py can be called either with `--dist-dir` or automatically graps the environment variable `"PACKAGE_DIST_DIR"` and sets it as default of `--dist-dir`.
This will fix that this python script does not crash anymore when `--dist-dir` is given but `"PACKAGE_DIST_DIR"` not set.

Allow write_torch_version.py to run without env variable

---

.github/workflows/build_portable_linux_python_packages.yml
.github/workflows/build_windows_python_packages.yml
.github/workflows/ci_linux.yml
.github/workflows/ci_windows.yml

Progress on https://github.com/ROCm/TheRock/issues/1559. This gets us presubmit coverage for building the Python packages and running sanity check tests on them (fully implemented on Windows, almost finished on Linux).
As mentioned on https://github.com/ROCm/TheRock/pull/1596, the new `build_*_python_packages.yml` workflows do not yet upload the packages they build anywhere and only run sanity checks on the current (CPU build) machine. Once the workflows upload we can chain another `test_python_packages.yml` workflow similar to how `test_artifacts.yml` is already connected.
The plumbing here exposed a few issues that I'm ignoring in this PR:
1. `artifact_run_id` is overloaded now, working with `use_prebuilt_artifacts` _and_ standard fully pipelined build/test/release runs. See the …

[ci] Call build_*_python_packages in ci_*.yml workflows.

---

build_tools/fetch_artifacts.py
build_tools/install_rocm_from_artifacts.py
build_tools/packaging/linux/build_package.py
build_tools/tests/fetch_artifacts_test.py
external-builds/pytorch/README.md

This PR changes `fetch_artifacts.py` to _exclusively_ use include/exclude patterns for filtering artifact names to fetch. The ability to conveniently filter for "base artifacts" and individual components with flag options like `--blas --test` was retained in `install_rocm_from_artifacts.py` and supporting code was moved there. 
This follows up on https://github.com/ROCm/TheRock/pull/1607 where the build was broken and fixed by https://github.com/ROCm/TheRock/pull/1638. This script had multiple overlapping code paths for different types of artifact name filtering and download preparation, so making changes safely across all code paths was harder than it needed to be.
Support for filter patterns was added in https://github.com/ROCm/TheRock/pull/1251.
Other changes included here:
* Perform …

Move component filtering fully from fetch_artifacts to install script.

---

math-libs/BLAS/CMakeLists.txt

Since hipblaslt is migrating to `add_subdirectory` for rocroller consumption, but TheRock still uses standalone builds via `find_package`, a variable needs to be added to control the code flow between these two builds modes.
Add `-DHIPBLASLT_ENABLE_THEROCK=ON` to the hipblaslt build. This PR is intended to align with https://github.com/ROCm/rocm-libraries/pull/1588, which resolves an API inconsistency between the rocroller_host in hipblaslt while also updating the dependency mechanism to `add_subdirectory`.
TheRock CI testing through rocm-libraries
See the latest build results for TheRock CI here: https://github.com/ROCm/rocm-libraries/pull/1588

Add variable to enforce find_package when building hipblaslt

---

build_tools/setup_ccache.py
cmake/therock_amdgpu_targets.cmake

* Loads an optional target database file (assumes the invocation has set CMAKE_MODULE_PATH appropriately to find it) allowing non-default targets to be configured.
* Adds a `--remote` option to ccache setup.

A couple of ergonomics discovered while developing out of tree.

---

compiler/pre_hook_amd-llvm.cmake

Currently mainline does not have the code to take advantage of these options. This is to support amd-staging builds that are in progress.
Add support for building libompdevice.a as it is currently missing from staging builds.

[compiler] - Add cmake support for building libompdevice.a

---

external-builds/pytorch/README.md

Follow-up to https://github.com/ROCm/TheRock/pull/1598, making support status easier to interpret.
See also https://github.com/ROCm/TheRock/issues/1408 and https://github.com/ROCm/TheRock/issues/1619.

[doc] Adjust support table formatting for aotriton/Linux.

---

build_tools/github_actions/amdgpu_family_matrix.py

Currently, mi355 tests are incredibly flaky due to networking issues (which is a cluster issue). Worked with OSSCI to figure out the root cause, however, it seems to be a conductor mi355 issue that is causing issues with other teams.
This issue may not be resolved for some time, so to prevent flaky results, we will be disabling for the time being
Issue to reenable #1660

[ci] Disable mi355 test machines

---

RELEASES.md
build_tools/packaging/python/templates/rocm/src/rocm_sdk/__main__.py

This adds an `init` option and some more documentation to make expanding the development contents more accessible.
Closes #1239.

Add `init` option to `rocm-sdk`

---

patches/amd-mainline/rocm-libraries/0010-Patch-gemm.cpp-to-work-with-latest-rocRoller.patch

* Bump rocm-libraries to HEAD.
* Patch hipBLASLt to allow building with latest rocRoller changes.

Bump rocm-libraries submodule 20251002

---

build_tools/_therock_utils/pattern_match.py
build_tools/fileset_tool.py

Progress on #481
Solving the error below:
```
[build] [34/49  67% :: 52.394] Merging sub-project dist directory for hipcc
[build] FAILED: compiler/hipcc/stamp/dist.stamp D:/projects/TheRock/build/compiler/hipcc/stamp/dist.stamp 
[build] C:\Windows\system32\cmd.exe /C "cd /D D:\projects\TheRock\build\compiler && d:\projects\TheRock\.venv\Scripts\python D:/projects/TheRock/build_tools/fileset_tool.py copy D:/projects/TheRock/build/compiler/hipcc/dist D:/projects/TheRock/build/compiler/hipcc/stage D:/projects/TheRock/build/third-party/sysdeps/windows/zlib/build/stage D:/projects/TheRock/build/third-party/sysdeps/windows/zstd/build/stage D:/projects/TheRock/build/compiler/amd-llvm/stage && "C:\Program Files\CMake\bin\cmake.exe" -E touch …
```

Add retry logic for PermissionError in `pattern_match.py`

---

build_tools/github_actions/fetch_test_configurations.py

typically, rocprim takes around 8mins for linux and around 15 mins for windows. recently, there have been long timeout issues with `device_select`, which causes the test to timeout after 1h. 
This PR adjusts the rocprim timeout to catch this issue earlier. I'm actively working with the prim team to figure out and resolve this error

[ci] adjust rocprim timeout time

---

third-party/CMakeLists.txt
third-party/fftw3/CMakeLists.txt
third-party/fftw3/artifact_fftw3.toml
third-party/fftw3/artifact_fftw3f.toml

Add the latest 3.3.10 fftw3 (double precision) and fftw3f (float/single precision) libraries to TheRock.
Libraries are build with the multi-thread support.
Libraries are also build with the cmake and in this way they will automatically include the
FFTW3Configure.cmake and FFTW3fConfigure.cmake and other related cmake files that can
be used by cmake to find these libraries. When libraries are found, these scripts set variables like
FFTW3_FOUND and FFTW3f_FOUND and target properties FFTW3::fftw3 and FFTW3::fftw3f.
These cmake helper files are not produced if the fftw is build with the 
autoconf/configure/make way which is the reason why they are not included
in the fftw-packages that many linux distributions provide.
In those cases applications often use custom FindFFTW.cmake where the …

Add fftw3 and fftw3f 3.3.10 libraries

---

dockerfiles/build_manylinux_x86_64.Dockerfile

Description
This PR addresses [#1707](https://github.com/ROCm/TheRock/issues/1707)
by removing the devel packages and OpenMPI 5.0.8 source build introduced in [#1517](https://github.com/ROCm/TheRock/pull/1517)
.
A separate workflow was added in [commit cd0270b8](https://github.com/ROCm/TheRock/commit/cd0270b8be590be0f536121834bfe14c8ea9cc6b)
to handle building and publishing the RCCL/RCCL-Tests manylinux Docker image with OMPI 5.0.8 support.
This separation ensures:
Devel packages (e.g., numactl) are no longer bundled in the build image.
Reduced risk of regressions due to overlapping dependencies already provided by TheRock.
Clear isolation between the main build image and the OMPI-specific environment.
Together with the OMPI publishing workflow, this PR fully resolves once workflows are …

Clean up Docker image by removing devel packages and OMPI source build

---

external-builds/pytorch/pytorch_triton_repo.py
external-builds/pytorch/repo_management.py

Fixes missed out necessary changes from `--repo` to `--checkout-dir` in `external-builds/pytorch/repo_management.py` and `external-builds/pytorch/pytorch_triton_repo.py`

Fix the refactor of pytorch build_tools
