math-libs/CMakeLists.txt, third-party/CMakeLists.txt, third-party/msgpack-cxx/CMakeLists.txt
=> Add msgpack-cxx

patches/amd-mainline/hipBLASLt/0001-Add-explicit-CMake-flags-for-specifying-Tensile-tool.patch, patches/amd-mainline/hipBLASLt/0002-Update-find_package-for-msgpack-to-work-with-5.x-and.patch
Put a PR upstream: https://github.com/ROCm/hipBLASLt/pull/1616
=> Patch hipblaslt to be able to use msgpack 5.x or 6.x.

build_tools/fetch_sources.py, math-libs/CMakeLists.txt, math-libs/artifact-prim.toml, math-libs/artifact-solver.toml, math-libs/post_hook_rocSOLVER.cmake, math-libs/rocPRIM, math-libs/rocSOLVER, third-party/CMakeLists.txt, third-party/fmt/CMakeLists.txt
Adds rocSOLVER and its dependencies rocPRIM and fmt.
=> Add rocSOLVER and its dependencies

compiler/pre_hook_amd-llvm.cmake
Progress on #69 (the amdgpu-arch tool was failing).
=> Configure rpath in llvm so it can find runtime libraries.

docs/development/windows_support.md
=> Link to official pages explaining Windows support.

dockerfiles/build_manylinux_x86_64.Dockerfile, dockerfiles/install_awscli.sh
Installs the AWS CLI, required to upload artifacts to an S3 bucket, in the Docker image.
=> Install AWS CLI

build_tools/fileset_tool.py
Address minor incompatibility issue with Python 3.11 since follow_symlinks was added in multiple places as part of Python 3.12 https://docs.python.org/3/library/pathlib.html#pathlib.Path.exists
=> Fix Python 3.11 incompatbility in fileset_tool.py

build_tools/fetch_sources.py
Runs: `./build_tools/fetch_sources.py --remote`
=> Bump to mainline 20250305.

README.md, dockerfiles/cpubuilder/build_manylinux_x86_64.Dockerfile
Required to build client tests.
=> Install PyYAML

build_tools/linux_python_dist_split.py
=> Fix typos in `build_tools`

math-libs/BLAS/CMakeLists.txt, math-libs/BLAS/artifact-blas.toml, math-libs/BLAS/post_hook_rocBLAS.cmake
=> Build rocBLAS clients benchmarks

math-libs/BLAS/CMakeLists.txt, math-libs/BLAS/artifact-blas.toml, math-libs/BLAS/post_hook_hipBLASLt.cmake, patches/amd-mainline/hipBLASLt/0006-Build-hipblas-sequence-on-non-Ubuntu-systems.patch
=> Build hipBLASLt clients benchmarks

patches/amd-mainline/rocminfo/0001-Use-idomatic-approach-to-extending-CMAKE_MODULE_PATH.patch
=> Re-work patch to extend CMAKE_MODULE_PATH

external-builds/pytorch/smoke-tests/README.md, external-builds/pytorch/smoke-tests/pytorch_smoke_tests.py
Add smoke tests and README with disclaimer - prerequisite for #185
=> Add smoke tests and README with disclaimer

.github/workflows/ci.yml, .github/workflows/verify_docker_image.yml, external-builds/pytorch/smoke-tests/run_smoke_tests.sh
This PR runs a set of smoke tests on the docker container using the docker image from [here](https://github.com/ROCm/TheRock/pkgs/container/therock_pytorch_dev_ubuntu_24_04_gfx942)
Currently, the verification focuses on GFX942 target
The future work will be adding the multiple targets as matrix.
=> Add Docker image verification

.github/workflows/verify_docker_image.yml, external-builds/pytorch/smoke-tests/run_smoke_tests.sh
The PR adds proper flags for the shell script if any error occurs. If error happens, this will be reflected to the workflow.
It enhances https://github.com/ROCm/TheRock/pull/185
=> Add proper flags for error check  in shell script

docs/development/git_chores.md
This took a bit of experimentation to get right. Documenting the steps I took.
=> Add notes on how to change submodule branches.

.gitmodules
This will help with https://github.com/ROCm/TheRock/issues/36, since support for building CLR on Windows will require recent changes made to both CLR and HIP.
We also plan on moving other submodules closer to the latest development branches (staging/develop, depending on the repo).
Documentation for how these were updated: https://github.com/ROCm/TheRock/pull/322.
=> Switch core/HIP and core/clr from amd-mainline to amd-staging.

dockerfiles/pytorch-dev/pytorch_dev_ubuntu_24.04.Dockerfile
Works around #336 
Manual run can be seen: https://github.com/ROCm/TheRock/actions/runs/14209475508
=> Downgrade the cmake version to make it compatible

.pre-commit-config.yaml, docs/rfcs/README.md, docs/rfcs/RFC0001-BLAS-Stack-Build-Improvements.md
Add RFC for BLAS library stack improvements relating to build system changes and monorepo migration.
=> Add RFC for BLAS build improvements

build_tools/configure_ci.py
=> Fixing empty test targets

.github/workflows/portable_linux_package_matrix.yml
=> Adding actions write permission for Portable Linux Package Matrix

README.md, build_tools/provision_machine.py
Updating docs for provision.py
=> Updating docs for provision.py

comm-libs/CMakeLists.txt, comm-libs/artifact-rccl.toml, patches/amd-mainline/rccl/0001-Set-GTEST_BOTH_LIBRARIES-appropriately.patch
=> Enable building rccl tests

.gitmodules, build_tools/fetch_sources.py, comm-libs/CMakeLists.txt, comm-libs/artifact-rccl.toml, patches/amd-mainline/rccl-tests/0001-Link-Threads-Threads.patch
Adds rccl-tests to TheRock.
Closes #473
=> Add rccl-tests

dockerfiles/pytorch-dev/install_rocm_from_release.sh
Replace old script name with new one in the header comment
=> Update the script name on the comment section

docs/development/windows_support.md
Now working thanks to https://github.com/ROCm/TheRock/pull/476 and https://github.com/ROCm/TheRock/pull/492. Not yet built/tested on CI though.
=> Mark hipBLASLt as supported on Windows.

.github/workflows/release_portable_linux_packages.yml
Noticed errors for [Build Portable Linux Packages](https://github.com/ROCm/TheRock/actions/runs/14971367059/job/42052873942), this should resolve that
=> Fixing AWS configure issue

patches/amd-mainline/rocm_smi_lib/0001-Miscellaneous-CMake-fixes.patch
Bumps base and core submodules excluding `clr` which is addressed with #555 but requires a more recent version of PAL.
=> Bump base and core submodules 20250514

build_tools/fetch_artifacts.py
Worked with a user that didn't have aws cli installed. Errors were vagued, so this will help improve
tested on my local machine without s3
=> Adding s3 installation check

docs/development/windows_support.md
These are not rendered as expected:
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts
> Alerts cannot be nested within other elements.
=> [docs] Remove nested alerts from windows_support.md.

docs/development/windows_support.md
Related to https://github.com/ROCm/TheRock/issues/36. Also included a known issue / possible workaround for https://github.com/ROCm/TheRock/issues/651.
=> [windows] Add disclaimer and known issues links to docs.

external-builds/pytorch/README.md, external-builds/pytorch/build_pytorch_windows.sh
Related to https://github.com/ROCm/TheRock/issues/589.
=> [torch] Add current status to PyTorch docs.

version.json
Post 6.4 branches are presumptively 6.5, pending final official release alignment.
=> Raise version to 6.5.0

cmake/therock_subproject.cmake
Progress on https://github.com/ROCm/TheRock/issues/670. This lets me build `therock-dist` on Windows while having the HIP SDK installed.
The install has two side effects that interact with the build:
* Files at the installed location, which is by default something like `C:\Program Files\AMD\ROCm\6.2`
* Environment variables: `HIP_PATH` and (for example) `HIP_PATH_62`
* Note that the GUI installer from https://rocm.docs.amd.com/projects/install-on-windows/en/latest/how-to/install.html does _not_ put any of these directories on `PATH`, but users might
For the particular errors noted on that issue, we could also skate by with this patch to hipSOLVER: https://github.com/ROCm/hipSOLVER/pull/399, but doing this sort of sandboxing provides some defense in depth.
=> Unset HIP_PATH and related env vars for sub-projects.

build_tools/fetch_repo.py
This script can be used to clone a repository and get a specific branch, commit or pull request. The primary use case is to get a checkout a specific PR from the monorepo and build the project with TheRock.
=> Add `fetch_repo` helper script

RELEASES.md
* Fix section titles
* Move `Installing TheRock using pip` instructions up
=> Improve release documentation

build_tools/linux_portable_build.py
Fix for issues introduced in #733.
=> Fix build-python-only bug introduced in linux_portable_build.py.

.github/workflows/test_hipblaslt.yml, .github/workflows/test_rocblas.yml
Progress on https://github.com/ROCm/TheRock/issues/544.
BLAS is available for Windows yay, so adding tests!
Unfortunately for hipBLASLt, we are seeing issues loading the TensileLibrary (#681), so only enabling rocBLAS for now
=> [ci] Enabling rocBLAS tests for windows

.github/workflows/build_linux_pytorch_wheels.yml, .github/workflows/release_linux_pytorch_wheels.yml, build_tools/packaging/python/generate_release_index.py, external-builds/pytorch/build_prod_wheels.py
This PR adds:
1. The index generation for Pytorch wheels
2. Fix "+" problem in the wheel key link that is omitted in the indexer
3. Improved the modularity of the design with the input parameters
For instance:
"+" sign in the key replaced with the space which causes the error below:  
<Key>gfx94X-dcgpu/torch-2.7.0a0 rocmsdk20250530-cp312-cp312-linux_x86_64.whl</Key>
Correct one: 
<Key>gfx94X-dcgpu/torch-2.7.0a0+rocmsdk20250530-cp312-cp312-linux_x86_64.whl</Key>
The error seen in the browser:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>gfx94X-dcgpu/torch-2.7.0a0 rocmsdk20250530-cp312-cp312-linux_x86_64.whl</Key> …
```
=> Add index generation for Pytorch wheels

third-party/CMakeLists.txt, third-party/yaml-cpp/CMakeLists.txt
Adds yaml-cpp as a dependency for rocRoller.
=> Add yaml-cpp to the project

.github/workflows/release_linux_pytorch_wheels.yml
Add Python 3.13 to the workflow
=> Add Python 3.13 to the workflow

RELEASES.md
Continuing after https://github.com/ROCm/TheRock/pull/807.
Still more to do, checkpointing for now.
=> Iterate on documentation for pip installs.

RELEASES.md
Now showing how to verify that the install worked and giving a bit more information about what else to do after installing.
=> Iterate on "using installed packages" docs.

.github/workflows/release_windows_packages.yml
Follow-up to https://github.com/ROCm/TheRock/pull/825 now that these are working. Related to https://github.com/ROCm/TheRock/issues/542.
=> Enable release_windows_packages.yml schedule trigger.

.github/workflows/build_windows_pytorch_wheels.yml, .github/workflows/release_windows_pytorch_wheels.yml
Progress on https://github.com/ROCm/TheRock/issues/827. Again starting with just the boilerplate so I can test with `workflow_dispatch`. Will fill in the details in future PRs.
Tested at https://github.com/ScottTodd/TheRock/actions/runs/15619727527
=> Fork [build,release]_pytorch_wheels workflows for Windows.

.github/workflows/build_linux_pytorch_wheels.yml, .github/workflows/release_linux_pytorch_wheels.yml, .github/workflows/release_portable_linux_packages.yml, build_tools/third_party/s3_management/LICENSE, build_tools/third_party/s3_management/manage.py, build_tools/third_party/s3_management/update_dependencies.py, external-builds/pytorch/build_prod_wheels.py
* Forks
* https://github.com/pytorch/test-infra/blob/6105c6f94a6055fffdbbb7319f8fb10a45dae644/s3_management/manage.py
* https://github.com/pytorch/test-infra/blob/1ffc7f7b3b421b57c380de469e11744f54399f09/s3_management/update_dependencies.py
* Adapts the scripts to our needs.
* Adjusts our workflows to upload Python packages to a subfolder and use the new script to generate the index.
* Revises `release_linux_pytorch_wheels.yml` to allow inputs.
* Further starts to harmonize naming in the release workflows.
=> Generate a consolidated Python index

build_tools/fetch_artifacts.py
Splitting this change off from https://github.com/ROCm/TheRock/pull/772.
* Replaced tuple with `ArtifactDownloadRequest` dataclass. We can more easily attach metadata to this, use it in unit tests, and pass it between more functions without needing to remember what the tuple represents.
* Renamed some functions and variables to reflect what they _do_, not how they are implemented. This makes it easier to change implementations later without also needing to change the function names.
=> [NFC] Code style tweaks to fetch_artifacts.py.

patches/amd-mainline/rocm-core/0002-Force-gzip-to-overwrite-an-existing-changelog.patch
=> Add patch to overwrite existing changelog

build_tools/fetch_artifacts.py
This will help with building rocm sdk Python wheels from CI artifacts without needing to build from source locally. Progress on https://github.com/ROCm/TheRock/issues/827.
Prior to this, `fetch_artifacts.py` just downloaded the compressed `.tar.xz` archive files, without extracting them. The related `install_rocm_from_artifacts.py` script downloads the compressed files and flattens them during extraction. This extracts to one folder per archive, without merging or flattening.
I'm initially keeping the code close to where it is used for convenience and while I learn more about the architecture here, but I'd like to find a home for it in https://github.com/ROCm/TheRock/blob/main/build_tools/_therock_utils/artifacts.py, with documentation in …
=> Add support for extracting archives to fetch_artifacts.py.

.github/workflows/test_pytorch_wheels.yml
Add minimal workflow for pytorch testing - needed this to work on my branch
=> Add minimal workflow for pytorch testing

docs/development/adding_tests.md
As requested in standup, adding docs on how to add tests to TheRock
=> [docs] - Adding tests to TheRock

build_tools/github_actions/fetch_test_configurations.py, build_tools/github_actions/test_executable_scripts/test_hiprand.py, build_tools/github_actions/test_executable_scripts/test_rocrand.py, math-libs/CMakeLists.txt, math-libs/artifact-rand.toml
Adding hipRAND + rocRAND tests for both linux and windows
Closes #250 
Related #705 and #706 have been closed
=> [ci] - Adding RAND tests

.github/workflows/release_linux_pytorch_wheels.yml
RE-land https://github.com/ROCm/TheRock/pull/818
Tests: https://github.com/ROCm/TheRock/actions/runs/16019770390
=> [Re-land] Add Python 3.13 to the workflow

.github/workflows/ci_nightly.yml, README.md
Following up on https://github.com/ROCm/TheRock/pull/909#discussion_r2178416127.
=> Fix typo in "CI Nightly" workflow name, add status badge.

build_tools/packaging/python/templates/rocm/src/rocm_sdk/_devel.py
Progress on https://github.com/ROCm/TheRock/issues/827.
This replaces symlinks in the `_rocm_sdk_devel` folder of a Python install on Windows with hardlinks. Symlinks are not supported in Python wheels (see https://pep-previews--3786.org.readthedocs.build/pep-0778/ for a proposal to change that) so we expand a directory structure containing symlinks from a tarfile on demand. However, Windows has patchy support for symlinks (dependent on registry/policy settings), while hardlinks are more broadly available. For more background information on symlinks vs hardlinks, see https://stackoverflow.com/questions/185899/what-is-the-difference-between-a-symbolic-link-and-a-hard-link .
Tested:
* Locally on my gfx1100 machine with a source build
```bash
python .\build_tools\build_python_packages.py …
```
=> [windows] Convert symlinks to hardlinks during tarfile expansion.

.github/workflows/publish_pytorch_dev_docker.yml, build_tools/github_actions/fetch_package_targets.py, build_tools/github_actions/tests/fetch_package_targets_test.py
Previous hard-coded logic was okay, but this is an improvement to dynamically run tests
[Workflow tested here](https://github.com/ROCm/TheRock/actions/runs/16178835751) then correctly triggering and testing [pull and test workflow](https://github.com/ROCm/TheRock/actions/runs/16179730606)
=> [ci] - PyTorch docker cleanup to avoid hardcoded test targets

docs/development/windows_support.md, external-builds/pytorch/README.md
See https://github.com/ROCm/TheRock/issues/1040 and https://github.com/ROCm/TheRock/issues/910.
=> [torch][windows] Add links to recently filed issues.

docs/development/README.md, docs/development/github_actions_debugging.md
Copying some notes from https://github.com/ROCm/TheRock/issues/840 into a developer doc after using them for some of my own debugging.
=> Start docs/development/github_actions_debugging.md page.

.github/workflows/build_linux_packages.yml, .github/workflows/ci.yml, .github/workflows/ci_linux.yml, build_tools/github_actions/fetch_job_status.py, build_tools/github_actions/populate_redshift_db.py, requirements.txt
Added fetch_job_status.py and populate_redshift_db.py files along with workflow changes to populate redshift cluster db
=> Added fetch_job_status.py and populate_redshift_db.py files along with workflow changes

build_tools/github_actions/amdgpu_family_matrix.py
After determining runner issues, we were able to resolve and get runners working
Closes #1049
=> [ci] - Enable mi355 test machine

.github/workflows/ci.yml
Adding CI summary step for TheRock, will be useful later when locking down PRs
=> [ci] - Adding CI summary

build_tools/hack/build_env_diag.py
Now I can run the diagnostics script on my dev machine out of the box.
=> Make win32com import optional in build_env_diag.py.

core/CMakeLists.txt
Progress on https://github.com/ROCm/TheRock/issues/1321
Try to unblock #1296 with updated PAL
=> [windows] test rocm-systems integration with bump amdgpu-windows-interop to version 20250820

docs/packaging/python_packaging.md
Updated python_packaging.md to reflect the changes added in: https://github.com/ROCm/TheRock/pull/1269
=> [doc] Added a Target Family Selection section to python_packaging.md

.gitmodules, build_tools/fetch_sources.py
- Initially pointing to amd-mainline branch
=> Add spirv-llvm-translator submodule

build_tools/github_actions/github_actions_utils.py
=> Rebase on top of Geo's move of this logic.

cmake/therock_amdgpu_targets.cmake
Already documented here: https://github.com/ROCm/TheRock/blob/a880e83ac1861c3d5a2a33e1bcc6be55efe8ab21/RELEASES.md?plain=1#L89-L92
=> Add product name to gfx950 target.

.github/workflows/test_packages.yml, .github/workflows/test_pytorch_wheels.yml
Using the SHA from #1416  for `TheRock CI testing`
Also doing cleanup as docker image has gfortran
=> [ci] Utilizing new docker SHA for TheRock CI

compiler/pre_hook_amd-comgr.cmake, compiler/pre_hook_amd-llvm.cmake
- Start building spirv-llvm-translator as part of llvm-project
- Enable linking spirv-llvm-translator into comgr
=> Enable spirv-llvm-translator

docs/development/README.md, docs/development/adding_tests.md, docs/development/artifacts.md, docs/development/installing_artifacts.md
While adding hipDNN (#1689) I found that the adding_tests.md document was missing some details about how artifacts are being retrieved. Updating docs to explicitly indicate that artifact support for new components needs to be added, and some steps on how to add it.
I recommend viewing the doc changes in github instead of via diffs to see formatting.
Please navigate [here](https://github.com/ROCm/TheRock/blob/users/bharriso/update-testing-doc/docs/development/installing_artifacts.md).
=> Add documentation about installing artifacts
